import type { ConfigOf, Schema } from "@/lib/schema";
import type { PasswordConfig } from "./react/password";

export const passwordSchema = [
  {
    key: "label",
    label: "Label",
    description: "What the field is for.",
    group: "Content",
    type: "text",
    default: "New password",
    maxLength: 60,
  },
  {
    key: "hint",
    label: "Hint",
    description: "Advice under the label. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Use something you have not used elsewhere.",
    maxLength: 160,
  },
  {
    key: "minLength",
    label: "Shortest allowed",
    description: "Length does more for a password than any other rule.",
    group: "Behaviour",
    type: "number",
    default: 12,
    min: 6,
    max: 64,
  },
  {
    key: "requireNumber",
    label: "Needs a number",
    description: "Adds it to the rules and to the strength.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  {
    key: "requireUpper",
    label: "Needs a capital letter",
    description: "Adds it to the rules and to the strength.",
    group: "Behaviour",
    type: "boolean",
    default: false,
  },
  {
    key: "requireSymbol",
    label: "Needs a symbol",
    description: "Adds it to the rules and to the strength.",
    group: "Behaviour",
    type: "boolean",
    default: false,
  },
  {
    key: "showToggle",
    label: "Show password button",
    description: "Lets people check what they typed instead of guessing.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "showMeter",
    label: "Strength meter",
    description: "Four steps, with the word carrying the meaning and the bars only picturing it.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "showRules",
    label: "Rules list",
    description: "Each rule with whether it is met yet. Read out with the field.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "capsWarning",
    label: "Caps Lock warning",
    description: "Says so when Caps Lock is on, which is the usual cause of a rejected password.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The strength bars and focus rings. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the field and the button.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
  {
    key: "ruleLength",
    label: "Length rule",
    description: "{count} is the shortest length.",
    group: "Words",
    type: "text",
    default: "At least {count} characters",
    maxLength: 60,
  },
  {
    key: "ruleNumber",
    label: "Number rule",
    description: "Shown when a number is needed.",
    group: "Words",
    type: "text",
    default: "A number",
    maxLength: 60,
  },
  {
    key: "ruleUpper",
    label: "Capital rule",
    description: "Shown when a capital is needed.",
    group: "Words",
    type: "text",
    default: "A capital letter",
    maxLength: 60,
  },
  {
    key: "ruleSymbol",
    label: "Symbol rule",
    description: "Shown when a symbol is needed.",
    group: "Words",
    type: "text",
    default: "A symbol, such as ! or ?",
    maxLength: 60,
  },
  {
    key: "metText",
    label: "Met",
    description: "Read out after a rule that is met.",
    group: "Words",
    type: "text",
    default: "(met)",
    maxLength: 30,
  },
  {
    key: "notMetText",
    label: "Not met",
    description: "Read out after a rule still to meet.",
    group: "Words",
    type: "text",
    default: "(not met yet)",
    maxLength: 30,
  },
  {
    key: "strengthText",
    label: "Strength",
    description: "Said as it is typed. {level} is one of the four below.",
    group: "Words",
    type: "text",
    default: "Password strength: {level}",
    maxLength: 60,
  },
  {
    key: "emptyText",
    label: "Empty",
    description: "The level before anything is typed.",
    group: "Words",
    type: "text",
    default: "Enter a password",
    maxLength: 40,
  },
  {
    key: "weakText",
    label: "Weak",
    description: "The lowest level.",
    group: "Words",
    type: "text",
    default: "Weak",
    maxLength: 20,
  },
  {
    key: "fairText",
    label: "Fair",
    description: "The second level.",
    group: "Words",
    type: "text",
    default: "Fair",
    maxLength: 20,
  },
  {
    key: "goodText",
    label: "Good",
    description: "The third level.",
    group: "Words",
    type: "text",
    default: "Good",
    maxLength: 20,
  },
  {
    key: "strongText",
    label: "Strong",
    description: "The top level.",
    group: "Words",
    type: "text",
    default: "Strong",
    maxLength: 20,
  },
  {
    key: "showText",
    label: "Show",
    description: "The button that shows the password.",
    group: "Words",
    type: "text",
    default: "Show",
    maxLength: 20,
  },
  {
    key: "hideText",
    label: "Hide",
    description: "The same button while it is shown.",
    group: "Words",
    type: "text",
    default: "Hide",
    maxLength: 20,
  },
  {
    key: "toggleSuffix",
    label: "Button, read out",
    description: "Read out after Show or Hide.",
    group: "Words",
    type: "text",
    default: "password",
    maxLength: 30,
  },
  {
    key: "capsText",
    label: "Caps Lock",
    description: "Said when Caps Lock is on.",
    group: "Words",
    type: "text",
    default: "Caps Lock is on.",
    maxLength: 60,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof passwordSchema>, PasswordConfig> = true;
