import type { ConfigOf, Schema } from "@/lib/schema";
import type { CartConfig } from "./react/cart";

export const cartSchema = [
  {
    key: "title",
    label: "Title",
    description: "Heading at the top of the basket.",
    group: "Content",
    type: "text",
    default: "Your basket",
    maxLength: 60,
  },
  {
    key: "lines",
    label: "Lines",
    description: "What is in the basket to start with. Prices are plain numbers; the symbol comes from the currency.",
    group: "Content",
    type: "list",
    default: [
      { name: "Field notebook", variant: "A5, dotted", price: "18.00", quantity: "2" },
      { name: "Drafting pencil", variant: "0.5 mm", price: "24.50", quantity: "1" },
      { name: "Ink refill", variant: "Black, pack of three", price: "9.00", quantity: "1" },
    ],
    fields: [
      { key: "name", label: "Name", maxLength: 60 },
      { key: "variant", label: "Option", maxLength: 60 },
      { key: "price", label: "Price each", maxLength: 12 },
      { key: "quantity", label: "Quantity", maxLength: 3 },
    ],
    maxItems: 8,
    itemLabel: "Line",
  },
  {
    key: "checkoutText",
    label: "Checkout button text",
    description: "Name the action.",
    group: "Content",
    type: "text",
    default: "Checkout",
    maxLength: 40,
  },
  {
    key: "checkoutHref",
    label: "Checkout link",
    description: "Where the button goes.",
    group: "Content",
    type: "text",
    default: "/checkout",
    maxLength: 200,
    format: "url",
  },
  {
    key: "continueText",
    label: "Second action text",
    description: "Goes back to shopping, or closes the drawer.",
    group: "Content",
    type: "text",
    default: "Continue shopping",
    maxLength: 40,
  },
  {
    key: "emptyText",
    label: "Empty basket text",
    description: "Shown once every line has been removed.",
    group: "Content",
    type: "text",
    default: "Your basket is empty.",
    maxLength: 140,
  },
  {
    key: "layout",
    label: "Layout",
    description: "A panel on the page, or a drawer that slides in over it.",
    group: "Behaviour",
    type: "select",
    default: "panel",
    options: ["panel", "drawer"],
  },
  {
    key: "openText",
    label: "Open button text",
    description: "The button that opens the drawer. The number of items is added after it.",
    group: "Behaviour",
    type: "text",
    default: "Basket",
    maxLength: 40,
    dependsOn: { key: "layout", equals: "drawer" },
  },
  {
    key: "currency",
    label: "Currency",
    description: "Prices are written by hand, not by locale, so every visitor sees the same figures.",
    group: "Behaviour",
    type: "select",
    default: "GBP",
    options: ["GBP", "USD", "EUR"],
  },
  {
    key: "quantityStepper",
    label: "Quantity stepper",
    description: "Minus and plus buttons with a box between them. Off shows the quantity as text.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "removeButton",
    label: "Remove button",
    description: "Takes a line out of the basket and says so.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "shipping",
    label: "Delivery line",
    description: "Adds delivery to the totals.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "shippingCost",
    label: "Delivery cost",
    description: "A flat rate, as a plain number.",
    group: "Add-ons",
    type: "text",
    default: "4.95",
    maxLength: 12,
    dependsOn: { key: "shipping", equals: true },
  },
  {
    key: "freeShippingOver",
    label: "Free delivery over",
    description: "Shows how much more is needed, with a progress bar. Zero switches it off.",
    group: "Add-ons",
    type: "number",
    default: 50,
    min: 0,
    max: 500,
    dependsOn: { key: "shipping", equals: true },
  },
  {
    key: "taxNote",
    label: "Note under the totals",
    description: "Tax or delivery small print. Leave empty to drop it.",
    group: "Add-ons",
    type: "text",
    default: "Tax included. Delivery calculated at checkout.",
    maxLength: 140,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The checkout button and the progress bar. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the panel, buttons and boxes.",
    group: "Style",
    type: "number",
    default: 10,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof cartSchema>, CartConfig> = true;
