import type { ConfigOf, Schema } from "@/lib/schema";
import type { RatingConfig } from "./react/rating";

export const ratingSchema = [
  {
    key: "label",
    label: "Label",
    description: "Names the group when someone is picking a rating.",
    group: "Content",
    type: "text",
    default: "Rate this part",
    maxLength: 80,
  },
  {
    key: "mode",
    label: "Kind",
    description: "Pick a rating, or show one that has already been given.",
    group: "Behaviour",
    type: "select",
    default: "pick",
    options: ["pick", "show"],
  },
  { key: "max", label: "Stars", group: "Behaviour", type: "number", default: 5, min: 2, max: 10 },
  {
    key: "halfStars",
    label: "Half stars",
    description:
      "Lets a rating be picked in halves. Each half has to stay 24px across, so the stars are drawn larger.",
    group: "Behaviour",
    type: "boolean",
    default: false,
  },
  {
    key: "value",
    label: "Value",
    description: "The starting choice, or the average to show. Averages can have a decimal.",
    group: "Behaviour",
    type: "number",
    default: 4,
    min: 0,
    max: 10,
    step: 0.1,
  },
  {
    key: "showValue",
    label: "Show the number",
    description: "In words beside the stars, so the rating isn't shown by shape alone.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "countText",
    label: "Extra note",
    description: "Free text beside the stars, e.g. how many ratings. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "",
    maxLength: 60,
  },
  {
    key: "name",
    label: "Form field name",
    description: "For picking. Submits the number of stars.",
    group: "Add-ons",
    type: "text",
    default: "rating",
    maxLength: 40,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  { key: "accentColor", label: "Star colour", group: "Style", type: "color", default: "#e6a700" },
  {
    key: "scoreText",
    label: "Score",
    description: "Says a score. {value} and {max} are numbers.",
    group: "Words",
    type: "text",
    default: "{value} out of {max}",
    maxLength: 60,
  },
  {
    key: "outOfText",
    label: "Out of",
    description: "Shown after the score's number. {max} is the most.",
    group: "Words",
    type: "text",
    default: "out of {max}",
    maxLength: 40,
  },
  {
    key: "starOne",
    label: "One star",
    description: "Read out for a one-star choice. {count} is 1.",
    group: "Words",
    type: "text",
    default: "{count} star",
    maxLength: 40,
  },
  {
    key: "starMany",
    label: "Stars",
    description: "Read out for every other choice. {count} is the number.",
    group: "Words",
    type: "text",
    default: "{count} stars",
    maxLength: 40,
  },
  {
    key: "noneText",
    label: "Not rated",
    description: "Said before a star is picked.",
    group: "Words",
    type: "text",
    default: "Not rated yet",
    maxLength: 60,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof ratingSchema>, RatingConfig> = true;
