import type { ConfigOf, Schema } from "@/lib/schema";
import type { SortableListConfig } from "./react/sortable-list";

export const sortableListSchema = [
  {
    key: "label",
    label: "Name",
    description: "Shown above the list, and names it for screen readers.",
    group: "Content",
    type: "text",
    default: "Your priorities",
    maxLength: 60,
  },
  {
    key: "hint",
    label: "Hint",
    description: "Under the name. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Drag a handle, or press Space on it and use the arrow keys.",
    maxLength: 160,
  },
  {
    key: "items",
    label: "Items",
    description: "In their starting order.",
    group: "Content",
    type: "list",
    default: [
      { label: "Fix the checkout bug" },
      { label: "Write release notes" },
      { label: "Review the design system PR" },
      { label: "Plan next sprint" },
      { label: "Update dependencies" },
    ],
    fields: [{ key: "label", label: "Text", maxLength: 80 }],
    maxItems: 20,
    itemLabel: "Item",
  },
  {
    key: "moveButtons",
    label: "Move up and down buttons",
    description: "A way to reorder without dragging, which WCAG 2.2 asks for. Keep it unless you offer another.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "numbered",
    label: "Numbers",
    description: "Shows each item's position.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The outline of the item being moved, and the focus ring.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "howText",
    label: "How to move",
    description: "Read out for each handle: how to move a row by keyboard.",
    group: "Words",
    type: "text",
    default: "Press Space to pick up, the up and down arrows to move, Space again to drop, and Escape to cancel.",
    maxLength: 200,
  },
  {
    key: "positionText",
    label: "Position",
    description: "Used in the messages below. {index} and {total} are numbers.",
    group: "Words",
    type: "text",
    default: "position {index} of {total}",
    maxLength: 60,
  },
  {
    key: "pickedText",
    label: "Picked up",
    description: "Said when a row is picked up. {item} and {position} are filled in.",
    group: "Words",
    type: "text",
    default: "Picked up {item}, {position}. Use the up and down arrows to move it, Space to drop, Escape to cancel.",
    maxLength: 200,
  },
  {
    key: "movedText",
    label: "Moved",
    description: "Said as a row moves. {item} and {position} are filled in.",
    group: "Words",
    type: "text",
    default: "{item} moved to {position}.",
    maxLength: 120,
  },
  {
    key: "droppedText",
    label: "Dropped",
    description: "Said when a row is put down. {item} and {position} are filled in.",
    group: "Words",
    type: "text",
    default: "{item} dropped at {position}.",
    maxLength: 120,
  },
  {
    key: "cancelledText",
    label: "Cancelled",
    description: "Said when a move is undone. {item} and {position} are filled in.",
    group: "Words",
    type: "text",
    default: "Cancelled. {item} is back at {position}.",
    maxLength: 120,
  },
  {
    key: "reorderLabel",
    label: "Handle",
    description: "Read out for each row's handle. {item} is the row.",
    group: "Words",
    type: "text",
    default: "Reorder {item}",
    maxLength: 80,
  },
  {
    key: "upLabel",
    label: "Up button",
    description: "Read out for each row's ↑. {item} is the row.",
    group: "Words",
    type: "text",
    default: "Move {item} up",
    maxLength: 80,
  },
  {
    key: "downLabel",
    label: "Down button",
    description: "Read out for each row's ↓. {item} is the row.",
    group: "Words",
    type: "text",
    default: "Move {item} down",
    maxLength: 80,
  },
  {
    key: "alreadyFirstText",
    label: "Already first",
    description: "Announced. {item} is the item.",
    group: "Words",
    type: "text",
    default: "{item} is already first.",
    maxLength: 160,
  },
  {
    key: "alreadyLastText",
    label: "Already last",
    description: "Announced.",
    group: "Words",
    type: "text",
    default: "{item} is already last.",
    maxLength: 160,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof sortableListSchema>, SortableListConfig> = true;
