import type { ConfigOf, Schema } from "@/lib/schema";
import type { ToastConfig } from "./react/toast";

export const toastSchema = [
  {
    key: "buttonText",
    label: "Trigger text",
    description: "The button that shows a normal message. In your project this is whatever saves the work.",
    group: "Content",
    type: "text",
    default: "Save changes",
    maxLength: 40,
  },
  {
    key: "message",
    label: "Message",
    description: "Say what happened, in the past tense.",
    group: "Content",
    type: "text",
    default: "Your changes have been saved.",
    maxLength: 160,
  },
  {
    key: "errorButtonText",
    label: "Problem trigger text",
    description: "The button that shows the problem message, so you can test both.",
    group: "Content",
    type: "text",
    default: "Save without a connection",
    maxLength: 40,
  },
  {
    key: "errorMessage",
    label: "Problem message",
    description: "Say what went wrong and what to do next.",
    group: "Content",
    type: "text",
    default: "We could not save your changes. Check your connection and try again.",
    maxLength: 200,
  },
  {
    key: "actionText",
    label: "Action inside the message",
    description: "One action, such as Undo. Leave empty for none.",
    group: "Content",
    type: "text",
    default: "Undo",
    maxLength: 30,
  },
  {
    key: "position",
    label: "Position",
    description: "Which corner or edge the messages stack in.",
    group: "Behaviour",
    type: "select",
    default: "bottom-right",
    options: ["top-right", "top-center", "bottom-right", "bottom-center"],
  },
  {
    key: "duration",
    label: "Seconds on screen",
    description: "0 keeps each message until it is closed. Any message pauses while you are inside the stack.",
    group: "Behaviour",
    type: "number",
    default: 6,
    min: 0,
    max: 20,
  },
  {
    key: "maxVisible",
    label: "Most messages at once",
    description: "Older messages drop off the top when more arrive.",
    group: "Behaviour",
    type: "number",
    default: 3,
    min: 1,
    max: 6,
  },
  {
    key: "closeButton",
    label: "Close button",
    description: "A cross on every message.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "icon",
    label: "Icon",
    description: "A tick or a warning mark. The colour is never the only signal: the words say it too.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The action inside a message and focus rings. Contrast-corrected before use.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of each message.",
    group: "Style",
    type: "number",
    default: 12,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof toastSchema>, ToastConfig> = true;
