import type { ConfigOf, Schema } from "@/lib/schema";
import type { CardFieldsConfig } from "./react/card-fields";

export const cardFieldsSchema = [
  { key: "title", label: "Title", group: "Content", type: "text", default: "Payment details", maxLength: 60 },
  {
    key: "amount",
    label: "Amount",
    description: "Shown on the button, as you write it (e.g. £49.00). Not calculated.",
    group: "Content",
    type: "text",
    default: "£49.00",
    maxLength: 20,
  },
  { key: "buttonText", label: "Button text", group: "Content", type: "text", default: "Pay", maxLength: 30 },
  { key: "showName", label: "Name on card", group: "Add-ons", type: "boolean", default: true },
  { key: "showPostcode", label: "Postcode", description: "Some providers use it to check the card.", group: "Add-ons", type: "boolean", default: true },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The pay button and the focus ring.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "nameLabel",
    label: "Name label",
    group: "Words",
    type: "text",
    default: "Name on card",
    maxLength: 40,
  },
  {
    key: "numberLabel",
    label: "Number label",
    group: "Words",
    type: "text",
    default: "Card number",
    maxLength: 40,
  },
  {
    key: "expiryLabel",
    label: "Expiry label",
    group: "Words",
    type: "text",
    default: "Expiry date",
    maxLength: 40,
  },
  {
    key: "expiryHint",
    label: "Expiry hint",
    group: "Words",
    type: "text",
    default: "MM/YY",
    maxLength: 20,
  },
  {
    key: "cvcLabel",
    label: "Security code label",
    group: "Words",
    type: "text",
    default: "Security code",
    maxLength: 40,
  },
  {
    key: "cvcBackHint",
    label: "Security code hint",
    description: "Most cards.",
    group: "Words",
    type: "text",
    default: "3 digits on the back",
    maxLength: 60,
  },
  {
    key: "cvcFrontHint",
    label: "Security code hint, Amex",
    description: "American Express cards.",
    group: "Words",
    type: "text",
    default: "4 digits on the front",
    maxLength: 60,
  },
  {
    key: "postcodeLabel",
    label: "Postcode label",
    group: "Words",
    type: "text",
    default: "Postcode",
    maxLength: 40,
  },
  {
    key: "nameMissingText",
    label: "No name",
    group: "Words",
    type: "text",
    default: "Enter the name on the card.",
    maxLength: 100,
  },
  {
    key: "postcodeMissingText",
    label: "No postcode",
    group: "Words",
    type: "text",
    default: "Enter the postcode.",
    maxLength: 100,
  },
  {
    key: "numberMissingText",
    label: "No card number",
    group: "Words",
    type: "text",
    default: "Enter the card number.",
    maxLength: 100,
  },
  {
    key: "numberBadText",
    label: "Wrong card number",
    group: "Words",
    type: "text",
    default: "Enter a valid card number. Check for a typo.",
    maxLength: 100,
  },
  {
    key: "expiryMissingText",
    label: "No expiry date",
    group: "Words",
    type: "text",
    default: "Enter the expiry date.",
    maxLength: 100,
  },
  {
    key: "expiryBadText",
    label: "Wrong expiry date",
    group: "Words",
    type: "text",
    default: "Enter the expiry date as MM/YY, for example 04/29.",
    maxLength: 100,
  },
  {
    key: "expiredText",
    label: "Expired card",
    group: "Words",
    type: "text",
    default: "This card has expired.",
    maxLength: 100,
  },
  {
    key: "cvcBadText",
    label: "Wrong security code",
    description: "{count} is 3, or 4 for American Express.",
    group: "Words",
    type: "text",
    default: "Enter the {count}-digit security code.",
    maxLength: 100,
  },
  {
    key: "errorPrefix",
    label: "Before an error",
    description: "Read out before each error, not shown.",
    group: "Words",
    type: "text",
    default: "Error:",
    maxLength: 20,
  },
  {
    key: "doneText",
    label: "All correct",
    description: "Announced when every field checks out.",
    group: "Words",
    type: "text",
    default: "Card details look right. This demo sends nothing.",
    maxLength: 120,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof cardFieldsSchema>, CardFieldsConfig> = true;
