import type { ConfigOf, Schema } from "@/lib/schema";
import type { SearchableSelectConfig } from "./react/searchable-select";

export const searchableSelectSchema = [
  {
    key: "label",
    label: "Label",
    description: "Text shown above the field. It also names the list.",
    group: "Content",
    type: "text",
    default: "Country",
    maxLength: 60,
  },
  {
    key: "placeholder",
    label: "Placeholder",
    description: "Hint inside the empty field. Keep instructions in the label or helper text.",
    group: "Content",
    type: "text",
    default: "Start typing to search",
    maxLength: 60,
  },
  {
    key: "options",
    label: "Options",
    description: "The choices people can pick from, in this order.",
    group: "Content",
    type: "list",
    default: [
      { label: "Australia" },
      { label: "Brazil" },
      { label: "Canada" },
      { label: "France" },
      { label: "Germany" },
      { label: "India" },
      { label: "Japan" },
      { label: "Kenya" },
      { label: "Mexico" },
      { label: "Netherlands" },
      { label: "New Zealand" },
      { label: "Spain" },
      { label: "United Kingdom" },
      { label: "United States" },
    ],
    fields: [{ key: "label", label: "Text", maxLength: 60 }],
    maxItems: 50,
    itemLabel: "Option",
  },
  {
    key: "noResultsText",
    label: "No results message",
    description: "Shown and announced when nothing matches what was typed.",
    group: "Content",
    type: "text",
    default: "No matches. Try a different spelling.",
    maxLength: 80,
  },
  {
    key: "name",
    label: "Form field name",
    description: "Name of the value sent when the form is submitted.",
    group: "Behaviour",
    type: "text",
    default: "country",
    maxLength: 40,
  },
  {
    key: "filter",
    label: "Matching",
    description: "How typed text is matched against the options.",
    group: "Behaviour",
    type: "select",
    default: "contains",
    options: ["contains", "startsWith"],
  },
  {
    key: "maxVisible",
    label: "Visible options",
    description: "How many options show before the list scrolls.",
    group: "Behaviour",
    type: "number",
    default: 6,
    min: 3,
    max: 10,
  },
  {
    key: "clearButton",
    label: "Clear button",
    description: "An × button that empties the field.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "helperText",
    label: "Helper text",
    description: "A short hint under the field.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "helperTextContent",
    label: "Helper text content",
    description: "The hint itself.",
    group: "Add-ons",
    type: "text",
    default: "Type to filter, then use the arrow keys or click to choose.",
    maxLength: 120,
    dependsOn: { key: "helperText", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "iosOnPhone",
    label: "iPhone look",
    description: "On iPhone and iPad: Apple's system font, iOS blue, and bigger rows to tap.",
    group: "Style",
    type: "boolean",
    default: true,
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The highlighted option and focus rings. Text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the field, list and options.",
    group: "Style",
    type: "number",
    default: 6,
    min: 0,
    max: 16,
  },
  {
    key: "size",
    label: "Size",
    description: "Height of the field and the options.",
    group: "Style",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof searchableSelectSchema>, SearchableSelectConfig> = true;
