import type { ConfigOf, Schema } from "@/lib/schema";
import type { PopoverConfig } from "./react/popover";

export const popoverSchema = [
  {
    key: "triggerText",
    label: "Trigger text",
    description: "The button that opens the popover.",
    group: "Content",
    type: "text",
    default: "Share this page",
    maxLength: 60,
  },
  {
    key: "heading",
    label: "Heading",
    description: "The first line inside. It also names the popover for screen readers.",
    group: "Content",
    type: "text",
    default: "Share",
    maxLength: 60,
  },
  {
    key: "body",
    label: "Text",
    description: "What this popover is for. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Anyone with the link can open this page. The link stops working when you turn sharing off.",
    maxLength: 300,
  },
  {
    key: "primaryText",
    label: "Main action",
    description: "The button inside the popover.",
    group: "Content",
    type: "text",
    default: "Copy link",
    maxLength: 40,
  },
  {
    key: "primaryHref",
    label: "Main action link",
    description: "Leave empty for a button your own code handles; set it to make the action a link.",
    group: "Content",
    type: "text",
    default: "",
    maxLength: 200,
    format: "url",
  },
  {
    key: "placement",
    label: "Placement",
    description: "Which side of the trigger the popover opens on.",
    group: "Behaviour",
    type: "select",
    default: "bottom",
    options: ["bottom", "top", "right"],
  },
  {
    key: "align",
    label: "Align",
    description: "Which edge of the trigger it lines up with. Ignored when it opens to the right.",
    group: "Behaviour",
    type: "select",
    default: "start",
    options: ["start", "end"],
  },
  {
    key: "closeOnOutside",
    label: "Close on outside click",
    description: "Off keeps it open until Escape or the close button.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  {
    key: "secondaryButton",
    label: "Second action",
    description: "A quieter action next to the main one.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "secondaryText",
    label: "Second action text",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "Turn off sharing",
    maxLength: 40,
    dependsOn: { key: "secondaryButton", equals: true },
  },
  {
    key: "closeButton",
    label: "Close button",
    description: "A cross in the corner, as well as Escape.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "arrow",
    label: "Arrow",
    description: "A small pointer towards the trigger.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "width",
    label: "Width (px)",
    description: "It never grows past the screen, whatever you set.",
    group: "Style",
    type: "number",
    default: 320,
    min: 200,
    max: 520,
    step: 10,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The main action and focus rings. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the popover and its buttons.",
    group: "Style",
    type: "number",
    default: 12,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof popoverSchema>, PopoverConfig> = true;
