import type { ConfigOf, Schema } from "@/lib/schema";
import type { FooterConfig } from "./react/footer";

export const footerSchema = [
  {
    key: "brandText",
    label: "Brand",
    description: "Your name, at the start of the footer.",
    group: "Content",
    type: "text",
    default: "Northwind",
    maxLength: 40,
  },
  {
    key: "tagline",
    label: "Tagline",
    description: "One line under the brand. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Design and build for teams that ship.",
    maxLength: 140,
  },
  {
    key: "links",
    label: "Footer links",
    description: "The links in the footer, in this order.",
    group: "Content",
    type: "list",
    default: [
      { label: "Work", href: "/work" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    fields: [
      { key: "label", label: "Text", maxLength: 40 },
      { key: "href", label: "Link", maxLength: 200, format: "url" },
    ],
    maxItems: 8,
    itemLabel: "Link",
  },
  {
    key: "legalText",
    label: "Legal line",
    description: "Copyright or company details, on the bottom line.",
    group: "Content",
    type: "text",
    default: "© Northwind Ltd. All rights reserved.",
    maxLength: 140,
  },
  {
    key: "navLabel",
    label: "Link group name",
    description: "Names this set of links for screen readers, so it is not confused with the main menu.",
    group: "Behaviour",
    type: "text",
    default: "Footer",
    maxLength: 40,
  },
  {
    key: "layout",
    label: "Layout",
    description: "Brand and links side by side, or everything stacked and centred.",
    group: "Behaviour",
    type: "select",
    default: "split",
    options: ["split", "stacked"],
  },
  {
    key: "social",
    label: "Social links",
    description: "A second row for your profiles elsewhere.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "socialLinks",
    label: "Profiles",
    description: "Name each service in the link text, so it makes sense read on its own.",
    group: "Add-ons",
    type: "list",
    default: [
      { label: "GitHub", href: "https://github.com" },
      { label: "LinkedIn", href: "https://linkedin.com" },
    ],
    fields: [
      { key: "label", label: "Text", maxLength: 40 },
      { key: "href", label: "Link", maxLength: 200, format: "url" },
    ],
    maxItems: 5,
    itemLabel: "Profile",
    dependsOn: { key: "social", equals: true },
  },
  {
    key: "backToTop",
    label: "Back to top link",
    description: "Jumps to the top of the page. It is a link, so it needs no JavaScript.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "backToTopText",
    label: "Back to top text",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "Back to top",
    maxLength: 40,
    dependsOn: { key: "backToTop", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "Link hover and focus. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "spacing",
    label: "Vertical space",
    description: "How much room the footer takes.",
    group: "Style",
    type: "select",
    default: "regular",
    options: ["compact", "regular", "spacious"],
  },
  {
    key: "topBorder",
    label: "Top border",
    description: "A line separating the footer from the page above it.",
    group: "Style",
    type: "boolean",
    default: true,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof footerSchema>, FooterConfig> = true;
