import type { ConfigOf, Schema } from "@/lib/schema";
import type { HeaderConfig } from "./react/header";

export const headerSchema = [
  {
    key: "logoText",
    label: "Logo text",
    description: "Your name or brand, top left.",
    group: "Content",
    type: "text",
    default: "Northwind",
    maxLength: 40,
  },
  {
    key: "links",
    label: "Navigation links",
    description: "The links in the bar, in this order.",
    group: "Content",
    type: "list",
    default: [
      { label: "Work", href: "/work" },
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Journal", href: "/journal" },
    ],
    fields: [
      { key: "label", label: "Text", maxLength: 40 },
      { key: "href", label: "Link", maxLength: 200, format: "url" },
    ],
    maxItems: 8,
    itemLabel: "Link",
  },
  {
    key: "menuLabel",
    label: "Menu button text",
    description: "Next to the menu icon on small screens.",
    group: "Content",
    type: "text",
    default: "Menu",
    maxLength: 20,
  },
  {
    key: "mobileBreakpoint",
    label: "Collapse below",
    description: "Under this width the links move into the menu.",
    group: "Behaviour",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
  {
    key: "sticky",
    label: "Stick to the top",
    description: "The header stays visible while the page scrolls.",
    group: "Behaviour",
    type: "boolean",
    default: false,
  },
  {
    key: "ctaButton",
    label: "Call-to-action button",
    description: "A filled button at the end of the navigation.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "ctaText",
    label: "Button text",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "Start a project",
    maxLength: 40,
    dependsOn: { key: "ctaButton", equals: true },
  },
  {
    key: "ctaHref",
    label: "Button link",
    description: "Where it goes.",
    group: "Add-ons",
    type: "text",
    default: "/contact",
    maxLength: 200,
    format: "url",
    dependsOn: { key: "ctaButton", equals: true },
  },
  {
    key: "skipLink",
    label: "Skip to content link",
    description: "Hidden until focused. Lets keyboard users jump past the navigation.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The call-to-action button. Its text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the button and links.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
  {
    key: "height",
    label: "Bar height",
    description: "How tall the header is.",
    group: "Style",
    type: "select",
    default: "regular",
    options: ["compact", "regular"],
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof headerSchema>, HeaderConfig> = true;
