import type { ConfigOf, Schema } from "@/lib/schema";
import type { SlotPickerConfig } from "./react/slot-picker";

export const slotPickerSchema = [
  { key: "heading", label: "Heading", group: "Content", type: "text", default: "Pick a time", maxLength: 60 },
  {
    key: "slots",
    label: "Slots",
    description: "Slots sharing a day are grouped under it. State is free or taken; taken cannot be picked.",
    group: "Content",
    type: "list",
    default: [
      { day: "Thursday 5 March", time: "09:00", state: "free" },
      { day: "Thursday 5 March", time: "09:30", state: "taken" },
      { day: "Thursday 5 March", time: "10:00", state: "free" },
      { day: "Thursday 5 March", time: "10:30", state: "free" },
      { day: "Friday 6 March", time: "11:00", state: "free" },
      { day: "Friday 6 March", time: "11:30", state: "taken" },
      { day: "Friday 6 March", time: "14:00", state: "free" },
      { day: "Monday 9 March", time: "09:00", state: "free" },
      { day: "Monday 9 March", time: "15:30", state: "free" },
    ],
    fields: [
      { key: "day", label: "Day", maxLength: 40 },
      { key: "time", label: "Time", maxLength: 12 },
      { key: "state", label: "free / taken", maxLength: 5 },
    ],
    maxItems: 60,
    itemLabel: "Slot",
  },
  {
    key: "timezoneNote",
    label: "Time zone note",
    description: "Say whose time zone these are. Times are printed as written, never converted.",
    group: "Content",
    type: "text",
    default: "Times are shown in your device's own time zone.",
    maxLength: 120,
  },
  { key: "confirmText", label: "Confirm button", group: "Content", type: "text", default: "Confirm this time", maxLength: 40 },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  { key: "accentColor", label: "Accent colour", group: "Style", type: "color", default: "#0f766e" },
  {
    key: "slotText",
    label: "A time",
    description: "Each time with its day. {day} and {time} are filled in.",
    group: "Words",
    type: "text",
    default: "{day} at {time}",
    maxLength: 60,
  },
  {
    key: "freeText",
    label: "Times free",
    description: "Said after the time zone note. {free} and {total} are counts.",
    group: "Words",
    type: "text",
    default: "{free} of {total} times are free.",
    maxLength: 80,
  },
  {
    key: "takenText",
    label: "Taken",
    description: "Said for a time that is gone.",
    group: "Words",
    type: "text",
    default: "(taken)",
    maxLength: 30,
  },
  {
    key: "noneText",
    label: "Nothing picked",
    description: "Said before a time is picked.",
    group: "Words",
    type: "text",
    default: "No time picked yet",
    maxLength: 60,
  },
  {
    key: "selectedText",
    label: "Picked",
    description: "Said once one is picked. {slot} is the time.",
    group: "Words",
    type: "text",
    default: "{slot} selected",
    maxLength: 80,
  },
  {
    key: "bookedText",
    label: "Booked",
    description: "Said after booking. {slot} is the time.",
    group: "Words",
    type: "text",
    default: "Booked for {slot}",
    maxLength: 80,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof slotPickerSchema>, SlotPickerConfig> = true;
