import fs from "node:fs";
import path from "node:path";
import { applyConfig } from "../lib/export";
import { parseConfig } from "../lib/schema";
import { readSource } from "../lib/sources";
import { datePickerSchema } from "../registry/date-picker/schema";

/** Configs under test, written as the same query strings the editor puts in its URL. */
export const variants = {
  default: "",
  range:
    "mode=range&format=YYYY-MM-DD&weekStartsOn=sunday&clearButton=true&todayButton=true&helperText=true&helperTextContent=Check-in+to+check-out",
};

const harnessPage = `import { notFound } from "next/navigation";
import { DatePicker } from "./date-picker";

// Generated by e2e/generate.ts — test harness for the exported React file.
export default function Page() {
  if (process.env.NODE_ENV === "production") notFound();
  return (
    <main className="p-8">
      <DatePicker />
    </main>
  );
}
`;

function write(file: string, content: string) {
  // Skip unchanged files so the running dev server doesn't recompile mid-test.
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

/** Writes the exported output for each variant: React into a harness route, vanilla as static files. */
export function generateOutputs() {
  for (const [variant, query] of Object.entries(variants)) {
    const config = parseConfig(datePickerSchema, new URLSearchParams(query));

    const harness = path.join(process.cwd(), "app/harness", `date-picker-${variant}`);
    write(path.join(harness, "date-picker.tsx"), applyConfig(readSource("date-picker/react/date-picker.tsx"), config));
    write(path.join(harness, "page.tsx"), harnessPage);

    const vanilla = path.join(process.cwd(), "e2e/.generated/vanilla", variant);
    write(path.join(vanilla, "index.html"), readSource("date-picker/vanilla/date-picker.html"));
    write(path.join(vanilla, "date-picker.css"), readSource("date-picker/vanilla/date-picker.css"));
    write(path.join(vanilla, "date-picker.js"), applyConfig(readSource("date-picker/vanilla/date-picker.js"), config));
  }
}
