import type { ConfigOf, Schema } from "@/lib/schema";
import type { ModalConfig } from "./react/modal";

export const modalSchema = [
  {
    key: "triggerText",
    label: "Trigger button text",
    description: "Label of the button that opens the modal.",
    group: "Content",
    type: "text",
    default: "Open dialog",
    maxLength: 40,
  },
  {
    key: "title",
    label: "Title",
    description: "Heading at the top. It's also the modal's accessible name.",
    group: "Content",
    type: "text",
    default: "Subscribe to updates",
    maxLength: 80,
  },
  {
    key: "body",
    label: "Body text",
    description: "The main message, read out together with the title.",
    group: "Content",
    type: "text",
    default: "Get an email when new components are released. Unsubscribe any time.",
    maxLength: 300,
  },
  {
    key: "primaryText",
    label: "Primary button text",
    description: "The main action.",
    group: "Content",
    type: "text",
    default: "Confirm",
    maxLength: 30,
  },
  {
    key: "initialFocus",
    label: "Focus when opened",
    description: "Title suits longer content; primary suits quick confirmations.",
    group: "Behaviour",
    type: "select",
    default: "title",
    options: ["title", "primary"],
  },
  {
    key: "closeOnBackdrop",
    label: "Close on backdrop click",
    description: "Clicking outside closes it. Escape always does.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  {
    key: "position",
    label: "Position",
    description: "A centred dialog, or a sheet attached to the bottom edge.",
    group: "Behaviour",
    type: "select",
    default: "center",
    options: ["center", "bottom"],
  },
  {
    key: "animation",
    label: "Open animation",
    description: "Switched off automatically for people who prefer reduced motion.",
    group: "Behaviour",
    type: "select",
    default: "fade",
    options: ["none", "fade", "scale"],
  },
  {
    key: "closeButton",
    label: "Close (×) button",
    description: "An × in the top corner.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "secondaryButton",
    label: "Secondary button",
    description: "A second, quieter button such as Cancel.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "secondaryText",
    label: "Secondary button text",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "Cancel",
    maxLength: 30,
    dependsOn: { key: "secondaryButton", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "iosOnPhone",
    label: "iPhone look",
    description: "On iPhone and iPad: Apple's system font, iOS blue, bigger buttons, and a sheet that slides up.",
    group: "Style",
    type: "boolean",
    default: true,
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "Primary buttons and focus rings. Text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the modal and its buttons.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
  {
    key: "size",
    label: "Width",
    description: "Maximum width of the modal.",
    group: "Style",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof modalSchema>, ModalConfig> = true;
