/*
 * English words → the other languages of lib/languages.ts (D94), for every part's Words options.
 * Shared words ("Close", "Clear all") are written once and serve every part that says them.
 * Written without a native speaker's check: [TODO: have each language reviewed].
 */
export type Translated = { es: string; fr: string; de: string; pt: string; ar: string; he: string; hi: string; ja: string; zh: string };

export const dictionary: Record<string, Translated> = {
  "(needed)": {"es": "(obligatorio)", "fr": "(obligatoire)", "de": "(Pflichtfeld)", "pt": "(obrigatório)", "ar": "(مطلوب)", "he": "(חובה)", "hi": "(आवश्यक)", "ja": "（必須）", "zh": "（必填）"},
  "Announcement": {"es": "Anuncio", "fr": "Annonce", "de": "Ankündigung", "pt": "Anúncio", "ar": "إعلان", "he": "הודעה", "hi": "घोषणा", "ja": "お知らせ", "zh": "公告"},
  "Applied filters": {"es": "Filtros aplicados", "fr": "Filtres appliqués", "de": "Aktive Filter", "pt": "Filtros aplicados", "ar": "عوامل التصفية المطبقة", "he": "מסננים פעילים", "hi": "लागू फ़िल्टर", "ja": "適用中のフィルター", "zh": "已应用的筛选条件"},
  "Breadcrumb": {"es": "Ruta de navegación", "fr": "Fil d'Ariane", "de": "Brotkrümelnavigation", "pt": "Trilha de navegação", "ar": "مسار التنقل", "he": "פירורי לחם", "hi": "ब्रेडक्रम्ब", "ja": "パンくずリスト", "zh": "面包屑导航"},
  "Carry on": {"es": "Continuar", "fr": "Continuer", "de": "Weiter", "pt": "Continuar", "ar": "متابعة", "he": "המשך", "hi": "आगे बढ़ें", "ja": "次へ", "zh": "继续"},
  "Clear all": {"es": "Borrar todo", "fr": "Tout effacer", "de": "Alle entfernen", "pt": "Limpar tudo", "ar": "مسح الكل", "he": "ניקוי הכול", "hi": "सब हटाएँ", "ja": "すべてクリア", "zh": "全部清除"},
  "Close": {"es": "Cerrar", "fr": "Fermer", "de": "Schließen", "pt": "Fechar", "ar": "إغلاق", "he": "סגירה", "hi": "बंद करें", "ja": "閉じる", "zh": "关闭"},
  "Close this message": {"es": "Cerrar este mensaje", "fr": "Fermer ce message", "de": "Diese Nachricht schließen", "pt": "Fechar esta mensagem", "ar": "إغلاق هذه الرسالة", "he": "סגירת ההודעה", "hi": "यह संदेश बंद करें", "ja": "このメッセージを閉じる", "zh": "关闭此消息"},
  "Country code": {"es": "Código de país", "fr": "Indicatif du pays", "de": "Ländervorwahl", "pt": "Código do país", "ar": "رمز الدولة", "he": "קידומת מדינה", "hi": "देश कोड", "ja": "国番号", "zh": "国家代码"},
  "Measure": {"es": "Medida", "fr": "Mesure", "de": "Kennzahl", "pt": "Medida", "ar": "المقياس", "he": "מדד", "hi": "माप", "ja": "項目", "zh": "指标"},
  "No filters applied": {"es": "No hay filtros aplicados", "fr": "Aucun filtre appliqué", "de": "Keine Filter aktiv", "pt": "Nenhum filtro aplicado", "ar": "لا توجد عوامل تصفية مطبقة", "he": "לא הוחלו מסננים", "hi": "कोई फ़िल्टर लागू नहीं", "ja": "フィルターは適用されていません", "zh": "未应用筛选条件"},
  "Not available": {"es": "No disponible", "fr": "Indisponible", "de": "Nicht verfügbar", "pt": "Indisponível", "ar": "غير متاح", "he": "לא זמין", "hi": "उपलब्ध नहीं", "ja": "選択できません", "zh": "不可用"},
  "Nothing picked": {"es": "Nada elegido", "fr": "Aucun choix", "de": "Nichts ausgewählt", "pt": "Nada escolhido", "ar": "لم يتم اختيار شيء", "he": "לא נבחר דבר", "hi": "कुछ नहीं चुना गया", "ja": "未選択", "zh": "未选择"},
  "Nothing picked yet": {"es": "Aún no has elegido nada", "fr": "Rien n'est encore choisi", "de": "Noch nichts ausgewählt", "pt": "Nada escolhido ainda", "ar": "لم يتم اختيار شيء بعد", "he": "עדיין לא נבחר דבר", "hi": "अभी कुछ नहीं चुना गया", "ja": "まだ選択されていません", "zh": "尚未选择"},
  "Notifications": {"es": "Notificaciones", "fr": "Notifications", "de": "Benachrichtigungen", "pt": "Notificações", "ar": "الإشعارات", "he": "התראות", "hi": "सूचनाएँ", "ja": "通知", "zh": "通知"},
  "Off": {"es": "Desactivado", "fr": "Désactivé", "de": "Aus", "pt": "Desligado", "ar": "معطّل", "he": "כבוי", "hi": "बंद", "ja": "オフ", "zh": "关"},
  "On": {"es": "Activado", "fr": "Activé", "de": "An", "pt": "Ligado", "ar": "مفعّل", "he": "פועל", "hi": "चालू", "ja": "オン", "zh": "开"},
  "{choice} picked": {"es": "Elegido: {choice}", "fr": "Choisi : {choice}", "de": "Ausgewählt: {choice}", "pt": "Escolhido: {choice}", "ar": "تم اختيار {choice}", "he": "נבחר: {choice}", "hi": "{choice} चुना गया", "ja": "{choice} を選択しました", "zh": "已选择 {choice}"},
  "{count} character left": {"es": "Queda {count} carácter", "fr": "{count} caractère restant", "de": "Noch {count} Zeichen", "pt": "Resta {count} caractere", "ar": "بقي {count} حرف", "he": "נותר {count} תו", "hi": "{count} अक्षर बाकी", "ja": "残り {count} 文字", "zh": "还剩 {count} 个字符"},
  "{count} character over the limit": {"es": "{count} carácter por encima del límite", "fr": "{count} caractère de trop", "de": "{count} Zeichen über dem Limit", "pt": "{count} caractere acima do limite", "ar": "{count} حرف فوق الحد", "he": "{count} תו מעבר למגבלה", "hi": "सीमा से {count} अक्षर अधिक", "ja": "{count} 文字オーバー", "zh": "超出 {count} 个字符"},
  "{count} characters left": {"es": "Quedan {count} caracteres", "fr": "{count} caractères restants", "de": "Noch {count} Zeichen", "pt": "Restam {count} caracteres", "ar": "بقي {count} حرفًا", "he": "נותרו {count} תווים", "hi": "{count} अक्षर बाकी", "ja": "残り {count} 文字", "zh": "还剩 {count} 个字符"},
  "{count} characters over the limit": {"es": "{count} caracteres por encima del límite", "fr": "{count} caractères de trop", "de": "{count} Zeichen über dem Limit", "pt": "{count} caracteres acima do limite", "ar": "{count} أحرف فوق الحد", "he": "{count} תווים מעבר למגבלה", "hi": "सीमा से {count} अक्षर अधिक", "ja": "{count} 文字オーバー", "zh": "超出 {count} 个字符"},
  "{count} filter applied: {filters}": {"es": "{count} filtro aplicado: {filters}", "fr": "{count} filtre appliqué : {filters}", "de": "{count} Filter aktiv: {filters}", "pt": "{count} filtro aplicado: {filters}", "ar": "عامل تصفية واحد مطبق: {filters}", "he": "מסנן אחד הוחל: {filters}", "hi": "{count} फ़िल्टर लागू: {filters}", "ja": "{count} 件のフィルターを適用中: {filters}", "zh": "已应用 {count} 个筛选条件：{filters}"},
  "{count} filters applied: {filters}": {"es": "{count} filtros aplicados: {filters}", "fr": "{count} filtres appliqués : {filters}", "de": "{count} Filter aktiv: {filters}", "pt": "{count} filtros aplicados: {filters}", "ar": "{count} عوامل تصفية مطبقة: {filters}", "he": "{count} מסננים הוחלו: {filters}", "hi": "{count} फ़िल्टर लागू: {filters}", "ja": "{count} 件のフィルターを適用中: {filters}", "zh": "已应用 {count} 个筛选条件：{filters}"},
  "{count} picked: {choices}": {"es": "{count} elegidos: {choices}", "fr": "{count} choisis : {choices}", "de": "{count} ausgewählt: {choices}", "pt": "{count} escolhidos: {choices}", "ar": "تم اختيار {count}: {choices}", "he": "{count} נבחרו: {choices}", "hi": "{count} चुने गए: {choices}", "ja": "{count} 件選択: {choices}", "zh": "已选择 {count} 项：{choices}"},
  "{entered} of {length} digits entered": {"es": "{entered} de {length} dígitos introducidos", "fr": "{entered} chiffres sur {length} saisis", "de": "{entered} von {length} Ziffern eingegeben", "pt": "{entered} de {length} dígitos inseridos", "ar": "تم إدخال {entered} من {length} أرقام", "he": "הוזנו {entered} מתוך {length} ספרות", "hi": "{length} में से {entered} अंक दर्ज", "ja": "{length} 桁中 {entered} 桁入力済み", "zh": "已输入 {entered}/{length} 位数字"},
  "{tax} at {percent}%": {"es": "{tax} al {percent} %", "fr": "{tax} à {percent} %", "de": "{tax} ({percent} %)", "pt": "{tax} a {percent}%", "ar": "{tax} بنسبة {percent}%", "he": "{tax} בשיעור {percent}%", "hi": "{tax} {percent}% पर", "ja": "{tax}（{percent}%）", "zh": "{tax}（{percent}%）"},
};
