// The parts catalogue: what exists, and what is planned (shown as coming, never as available).
// Each part has a name of its own from one family (ship's instruments) plus a plain description.

export type Part = {
  slug: string;
  /** The part's own name, e.g. "Almanac". */
  codename: string;
  /** What it is in plain words, e.g. "Date picker". */
  name: string;
  summary: string;
  pattern: string;
  /** Accent used for this part across the catalogue and its page. */
  accent: string;
  status: "in-stock" | "coming";
};

export const parts: Part[] = [
  {
    slug: "date-picker",
    codename: "Almanac",
    name: "Date picker",
    summary: "One date or a range, typed in your format, with month and year views and earliest/latest dates.",
    pattern: "APG Date Picker Dialog",
    accent: "#e6b24a",
    status: "in-stock",
  },
  {
    slug: "modal",
    codename: "Porthole",
    name: "Modal",
    summary: "Centred dialog or bottom sheet. Focus stays inside, Escape closes, motion respects reduced-motion settings.",
    pattern: "APG Dialog (Modal)",
    accent: "#5ad1c8",
    status: "in-stock",
  },
  {
    slug: "searchable-select",
    codename: "Sextant",
    name: "Searchable select",
    summary: "Type to filter a long list, pick with the keyboard or the mouse, with matches highlighted.",
    pattern: "APG Combobox",
    accent: "#f08a5d",
    status: "in-stock",
  },
  {
    slug: "form",
    codename: "Logbook",
    name: "Form with validation",
    summary: "Your rules, and error messages that say what went wrong and how to fix it.",
    pattern: "Native form + error summary",
    accent: "#9d7bea",
    status: "in-stock",
  },
  {
    slug: "header",
    codename: "Masthead",
    name: "Site header",
    summary: "Logo, links, call to action and a mobile menu that behaves.",
    pattern: "APG Disclosure navigation",
    accent: "#6fc36f",
    status: "in-stock",
  },
  {
    slug: "tabs",
    codename: "Compass",
    name: "Tabs",
    summary: "One area, several panels. Arrow keys move between tabs, in a row or down the side.",
    pattern: "APG Tabs",
    accent: "#5b9cf0",
    status: "in-stock",
  },
  {
    slug: "cart",
    codename: "Cargo",
    name: "Basket",
    summary: "Lines, quantities, removing, delivery and totals, as a panel or a drawer.",
    pattern: "Native dialog + live totals",
    accent: "#f2a65a",
    status: "in-stock",
  },
  {
    slug: "carousel",
    codename: "Capstan",
    name: "Carousel",
    summary: "A row of slides that scrolls, swipes and steps, with dots, a counter and optional rotation.",
    pattern: "APG Carousel",
    accent: "#43c6ac",
    status: "in-stock",
  },
  {
    slug: "mega-menu",
    codename: "Chartroom",
    name: "Mega menu",
    summary: "Several columns of links under one heading, opened by click or hover, closed by Escape.",
    pattern: "APG Disclosure navigation",
    accent: "#7f9cf5",
    status: "in-stock",
  },
  {
    slug: "footer",
    codename: "Keel",
    name: "Site footer",
    summary: "Brand, links, social profiles and the legal line. Plain HTML, no JavaScript.",
    pattern: "Landmark contentinfo",
    accent: "#c08457",
    status: "in-stock",
  },
  {
    slug: "cta",
    codename: "Beacon",
    name: "CTA section",
    summary: "Heading, supporting text and actions. Plain HTML, no JavaScript.",
    pattern: "Landmark section",
    accent: "#ef7ba4",
    status: "in-stock",
  },
  {
    slug: "accordion",
    codename: "Bellows",
    name: "Accordion",
    summary: "Sections that open one at a time, or all at once, with the content in the page from the start.",
    pattern: "APG Accordion",
    accent: "#d98cf0",
    status: "in-stock",
  },
  {
    slug: "tooltip",
    codename: "Pennant",
    name: "Tooltip",
    summary: "A short note on a control, opened by hover and by keyboard focus, closed by Escape.",
    pattern: "APG Tooltip",
    accent: "#8fd4c1",
    status: "in-stock",
  },
  {
    slug: "menu",
    codename: "Helm",
    name: "Dropdown menu",
    summary: "A button that opens a list of actions: arrow keys, type to jump, Escape to close.",
    pattern: "APG Menu Button",
    accent: "#f2c14e",
    status: "in-stock",
  },
  {
    slug: "popover",
    codename: "Spyglass",
    name: "Popover",
    summary: "An anchored panel you can use: focus moves in, Escape closes it and comes back out.",
    pattern: "Anchored dialog",
    accent: "#6fb3f2",
    status: "in-stock",
  },
  {
    slug: "toast",
    codename: "Klaxon",
    name: "Notifications",
    summary: "Messages that appear, announce themselves, pause while you read and clear themselves.",
    pattern: "ARIA live region",
    accent: "#f28b82",
    status: "in-stock",
  },
  {
    slug: "table",
    codename: "Manifest",
    name: "Data table",
    summary: "Rows that sort by value, select by row and stack into cards on a phone.",
    pattern: "HTML table + aria-sort",
    accent: "#7ed0b5",
    status: "in-stock",
  },
  {
    slug: "pagination",
    codename: "Ladder",
    name: "Pagination",
    summary: "Numbered pages with gaps, previous and next, as links or as buttons.",
    pattern: "Navigation + aria-current",
    accent: "#b39ddb",
    status: "in-stock",
  },
  {
    slug: "breadcrumbs",
    codename: "Wake",
    name: "Breadcrumbs",
    summary: "The trail back up the site, collapsing to first and current on a phone. No JavaScript.",
    pattern: "Navigation + aria-current",
    accent: "#9fd8a0",
    status: "in-stock",
  },
  {
    slug: "stepper",
    codename: "Course",
    name: "Stepper",
    summary: "Where you are in a multi-step flow, with each state said in words. No JavaScript.",
    pattern: "Navigation + aria-current=step",
    accent: "#e8a0bf",
    status: "in-stock",
  },
  {
    slug: "sidebar",
    codename: "Gangway",
    name: "Sidebar navigation",
    summary: "Sections of links with the current page marked, folding into a drawer on a phone.",
    pattern: "Navigation + disclosure",
    accent: "#86b6f6",
    status: "in-stock",
  },
  {
    slug: "upload",
    codename: "Hoist",
    name: "File upload",
    summary: "Choose or drop files, with the kind and size checked and every change announced.",
    pattern: "File input + drop area",
    accent: "#f0b86e",
    status: "in-stock",
  },
  {
    slug: "multi-select",
    codename: "Trawl",
    name: "Multi-select",
    summary: "Pick several from a long list, with each choice removable and every change announced.",
    pattern: "APG Combobox, multi-select",
    accent: "#7fd1e8",
    status: "in-stock",
  },
  {
    slug: "password",
    codename: "Cipher",
    name: "Password field",
    summary: "Rules read with the field, strength said in words, and a show button that says its state.",
    pattern: "Labelled input + live rules",
    accent: "#c3a6f0",
    status: "in-stock",
  },
  {
    slug: "otp",
    codename: "Semaphore",
    name: "One-time code",
    summary: "Boxes that fill as you type, take a pasted code whole, and say when the code is complete.",
    pattern: "Grouped inputs + one-time-code",
    accent: "#f6c177",
    status: "in-stock",
  },
  {
    slug: "slider",
    codename: "Fathom",
    name: "Range slider",
    summary: "One value or a range, on native range inputs that keep their keyboard and announce their unit.",
    pattern: "Native range inputs",
    accent: "#6ec6ca",
    status: "in-stock",
  },
  {
    slug: "search",
    codename: "Lookout",
    name: "Global search",
    summary: "Point it at any data, nested or flat, and search it from anywhere with ⌘K.",
    pattern: "APG Combobox in a dialog",
    accent: "#ffb86b",
    status: "in-stock",
  },
];

export const inStock = parts.filter((part) => part.status === "in-stock");
export const partBySlug = (slug: string) => parts.find((part) => part.slug === slug)!;
