// The parts catalogue: what exists, and what is planned (shown as coming, never as available).
// Each part has a name of its own from one family (ship's instruments) plus a plain description.

export type Part = {
  slug: string;
  /** What it is in plain words, e.g. "Date picker". */
  name: string;
  summary: string;
  pattern: string;
  /** Accent used for this part across the catalogue and its page. */
  accent: string;
  status: "in-stock" | "coming";
  /** Groups the catalogue so it can be filtered instead of scrolled. */
  category: Category;
};

export const categories = ["Inputs", "Navigation", "Overlays", "Feedback", "Content", "Page sections"] as const;
export type Category = (typeof categories)[number];

export const parts: Part[] = [
  {
    slug: "date-picker",
    category: "Inputs",
    name: "Date picker",
    summary: "One date or a range, typed in your format, with month and year views and earliest/latest dates.",
    pattern: "APG Date Picker Dialog",
    accent: "#e6b24a",
    status: "in-stock",
  },
  {
    slug: "modal",
    category: "Overlays",
    name: "Modal dialog",
    summary: "Centred dialog or bottom sheet. Focus stays inside, Escape closes, motion respects reduced-motion settings.",
    pattern: "APG Dialog (Modal)",
    accent: "#5ad1c8",
    status: "in-stock",
  },
  {
    slug: "searchable-select",
    category: "Inputs",
    name: "Searchable select",
    summary: "Type to filter a long list, pick with the keyboard or the mouse, with matches highlighted.",
    pattern: "APG Combobox",
    accent: "#f08a5d",
    status: "in-stock",
  },
  {
    slug: "form",
    category: "Inputs",
    name: "Form validation",
    summary: "Your rules, and error messages that say what went wrong and how to fix it.",
    pattern: "Native form + error summary",
    accent: "#9d7bea",
    status: "in-stock",
  },
  {
    slug: "header",
    category: "Page sections",
    name: "Site header",
    summary: "Logo, links, call to action and a mobile menu that behaves.",
    pattern: "APG Disclosure navigation",
    accent: "#6fc36f",
    status: "in-stock",
  },
  {
    slug: "tabs",
    category: "Navigation",
    name: "Tabs",
    summary: "One area, several panels. Arrow keys move between tabs, in a row or down the side.",
    pattern: "APG Tabs",
    accent: "#5b9cf0",
    status: "in-stock",
  },
  {
    slug: "cart",
    category: "Content",
    name: "Shopping cart",
    summary: "Lines, quantities, removing, delivery and totals, as a panel or a drawer.",
    pattern: "Native dialog + live totals",
    accent: "#f2a65a",
    status: "in-stock",
  },
  {
    slug: "carousel",
    category: "Content",
    name: "Carousel",
    summary: "A row of slides that scrolls, swipes and steps, with dots, a counter and optional rotation.",
    pattern: "APG Carousel",
    accent: "#43c6ac",
    status: "in-stock",
  },
  {
    slug: "mega-menu",
    category: "Navigation",
    name: "Mega menu",
    summary: "Several columns of links under one heading, opened by click or hover, closed by Escape.",
    pattern: "APG Disclosure navigation",
    accent: "#7f9cf5",
    status: "in-stock",
  },
  {
    slug: "footer",
    category: "Page sections",
    name: "Site footer",
    summary: "Brand, links, social profiles and the legal line. Plain HTML, no JavaScript.",
    pattern: "Landmark contentinfo",
    accent: "#c08457",
    status: "in-stock",
  },
  {
    slug: "cta",
    category: "Page sections",
    name: "Call to action section",
    summary: "Heading, supporting text and actions. Plain HTML, no JavaScript.",
    pattern: "Landmark section",
    accent: "#ef7ba4",
    status: "in-stock",
  },
  {
    slug: "accordion",
    category: "Content",
    name: "Accordion",
    summary: "Sections that open one at a time, or all at once, with the content in the page from the start.",
    pattern: "APG Accordion",
    accent: "#d98cf0",
    status: "in-stock",
  },
  {
    slug: "tooltip",
    category: "Overlays",
    name: "Tooltip",
    summary: "A short note on a control, opened by hover and by keyboard focus, closed by Escape.",
    pattern: "APG Tooltip",
    accent: "#8fd4c1",
    status: "in-stock",
  },
  {
    slug: "menu",
    category: "Navigation",
    name: "Dropdown menu",
    summary: "A button that opens a list of actions: arrow keys, type to jump, Escape to close.",
    pattern: "APG Menu Button",
    accent: "#f2c14e",
    status: "in-stock",
  },
  {
    slug: "popover",
    category: "Overlays",
    name: "Popover",
    summary: "An anchored panel you can use: focus moves in, Escape closes it and comes back out.",
    pattern: "Anchored dialog",
    accent: "#6fb3f2",
    status: "in-stock",
  },
  {
    slug: "toast",
    category: "Overlays",
    name: "Toast notifications",
    summary: "Messages that appear, announce themselves, pause while you read and clear themselves.",
    pattern: "ARIA live region",
    accent: "#f28b82",
    status: "in-stock",
  },
  {
    slug: "table",
    category: "Content",
    name: "Data table",
    summary: "Rows that sort by value, select by row and stack into cards on a phone.",
    pattern: "HTML table + aria-sort",
    accent: "#7ed0b5",
    status: "in-stock",
  },
  {
    slug: "pagination",
    category: "Navigation",
    name: "Pagination",
    summary: "Numbered pages with gaps, previous and next, as links or as buttons.",
    pattern: "Navigation + aria-current",
    accent: "#b39ddb",
    status: "in-stock",
  },
  {
    slug: "breadcrumbs",
    category: "Navigation",
    name: "Breadcrumbs",
    summary: "The trail back up the site, collapsing to first and current on a phone. No JavaScript.",
    pattern: "Navigation + aria-current",
    accent: "#9fd8a0",
    status: "in-stock",
  },
  {
    slug: "stepper",
    category: "Navigation",
    name: "Stepper",
    summary: "Where you are in a multi-step flow, with each state said in words. No JavaScript.",
    pattern: "Navigation + aria-current=step",
    accent: "#e8a0bf",
    status: "in-stock",
  },
  {
    slug: "sidebar",
    category: "Navigation",
    name: "Sidebar navigation",
    summary: "Sections of links with the current page marked, folding into a drawer on a phone.",
    pattern: "Navigation + disclosure",
    accent: "#86b6f6",
    status: "in-stock",
  },
  {
    slug: "upload",
    category: "Inputs",
    name: "File upload",
    summary: "Choose or drop files, with the kind and size checked and every change announced.",
    pattern: "File input + drop area",
    accent: "#f0b86e",
    status: "in-stock",
  },
  {
    slug: "multi-select",
    category: "Inputs",
    name: "Multi-select",
    summary: "Pick several from a long list, with each choice removable and every change announced.",
    pattern: "APG Combobox, multi-select",
    accent: "#7fd1e8",
    status: "in-stock",
  },
  {
    slug: "password",
    category: "Inputs",
    name: "Password field",
    summary: "Rules read with the field, strength said in words, and a show button that says its state.",
    pattern: "Labelled input + live rules",
    accent: "#c3a6f0",
    status: "in-stock",
  },
  {
    slug: "otp",
    category: "Inputs",
    name: "OTP input",
    summary: "Boxes that fill as you type, take a pasted code whole, and say when the code is complete.",
    pattern: "Grouped inputs + one-time-code",
    accent: "#f6c177",
    status: "in-stock",
  },
  {
    slug: "slider",
    category: "Inputs",
    name: "Range slider",
    summary: "One value or a range, on native range inputs that keep their keyboard and announce their unit.",
    pattern: "Native range inputs",
    accent: "#6ec6ca",
    status: "in-stock",
  },
  {
    slug: "search",
    category: "Navigation",
    name: "Search with suggestions",
    summary: "Point it at any data, nested or flat, and search it from anywhere with ⌘K.",
    pattern: "APG Combobox in a dialog",
    accent: "#ffb86b",
    status: "in-stock",
  },
  {
    slug: "time-picker",
    category: "Inputs",
    name: "Time picker",
    summary: "Type a time any common way or pick from a list, in 12- or 24-hour, with earliest and latest times.",
    pattern: "APG Combobox (editable)",
    accent: "#7dd3fc",
    status: "in-stock",
  },
  {
    slug: "tree-view",
    category: "Navigation",
    name: "Tree view",
    summary: "Folders and items as deep as you like, with the full arrow-key model, type-ahead and one Tab stop.",
    pattern: "APG Tree View",
    accent: "#a3e635",
    status: "in-stock",
  },
  {
    slug: "sortable-list",
    category: "Inputs",
    name: "Drag-and-drop list",
    summary: "Reorder by dragging, by keyboard or with move buttons, with every move announced.",
    pattern: "Toggle-button handles + live region",
    accent: "#f0abfc",
    status: "in-stock",
  },
  {
    slug: "drawer",
    category: "Overlays",
    name: "Drawer",
    summary: "A panel that slides in from a side or the bottom, keeps focus inside and closes with a swipe.",
    pattern: "APG Dialog (Modal)",
    accent: "#fca5a5",
    status: "in-stock",
  },
  {
    slug: "cookie-consent",
    category: "Overlays",
    name: "Cookie consent",
    summary: "Accept and reject side by side, nothing ticked in advance, and a way back to change your mind.",
    pattern: "Landmark region + dialog",
    accent: "#fdba74",
    status: "in-stock",
  },
  {
    slug: "card-fields",
    category: "Inputs",
    name: "Card payment fields",
    summary: "Number, expiry and code that format as you type, name the card type and catch typos before paying.",
    pattern: "Native form + autocomplete cc-*",
    accent: "#86efac",
    status: "in-stock",
  },
  {
    slug: "tour",
    category: "Overlays",
    name: "Product tour",
    summary: "Steps that point at parts of your page, move focus with them, and can be skipped at any moment.",
    pattern: "Non-modal dialog steps",
    accent: "#c4b5fd",
    status: "in-stock",
  },
  {
    slug: "feed",
    category: "Content",
    name: "Infinite feed",
    summary: "A list that loads more on request or as you scroll, keeps your place and says when it has ended.",
    pattern: "APG Feed",
    accent: "#67e8f9",
    status: "in-stock",
  },
  {
    slug: "lightbox",
    category: "Content",
    name: "Lightbox",
    summary: "Thumbnails that open a full-screen viewer with arrow keys, swipe, captions and focus kept inside.",
    pattern: "APG Dialog (Modal) gallery",
    accent: "#fde68a",
    status: "in-stock",
  },
  {
    slug: "resizable-panels",
    category: "Content",
    name: "Split panes",
    summary: "Two panels and a divider you can drag, move with the arrow keys or collapse with Enter.",
    pattern: "APG Window Splitter",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "switch",
    category: "Inputs",
    name: "Switch",
    summary: "An on/off control that says which it is in words, on a real checkbox so the keyboard comes free.",
    pattern: "Checkbox with role=switch",
    accent: "#7dd3fc",
    status: "in-stock",
  },
  {
    slug: "rating",
    category: "Inputs",
    name: "Rating",
    summary: "Stars to pick a rating, or an average shown as one figure a screen reader reads in full.",
    pattern: "Radio group / image",
    accent: "#fbbf24",
    status: "in-stock",
  },
  {
    slug: "segmented",
    category: "Inputs",
    name: "Segmented control",
    summary: "A handful of choices side by side, on radios, so arrow keys and forms work without script.",
    pattern: "Radio group",
    accent: "#a5b4fc",
    status: "in-stock",
  },
  {
    slug: "alert-banner",
    category: "Feedback",
    name: "Alert banner",
    summary: "Inline messages that say their tone in words first, and only interrupt when it is an error.",
    pattern: "role=alert / role=status",
    accent: "#fbbf24",
    status: "in-stock",
  },
  {
    slug: "skeleton",
    category: "Feedback",
    name: "Skeleton",
    summary: "Placeholder shapes while content loads, announced once in words instead of as empty boxes.",
    pattern: "role=status + hidden shapes",
    accent: "#cbd5e1",
    status: "in-stock",
  },
  {
    slug: "empty-state",
    category: "Feedback",
    name: "Empty state",
    summary: "A calm screen for nothing-to-show, saying what happened and exactly what to do next.",
    pattern: "Heading + actions",
    accent: "#94a3b8",
    status: "in-stock",
  },
  {
    slug: "avatar-group",
    category: "Content",
    name: "Avatar group",
    summary: "Overlapping faces or initials, with the extra people named rather than hidden behind a number.",
    pattern: "Labelled list of images",
    accent: "#f0abfc",
    status: "in-stock",
  },
  {
    slug: "badge",
    category: "Content",
    name: "Badge",
    summary: "Status pills whose words carry the meaning, so colour is never doing the work alone.",
    pattern: "List of labelled pills",
    accent: "#5eead4",
    status: "in-stock",
  },
  {
    slug: "tag-input",
    category: "Inputs",
    name: "Tag input",
    summary: "Type and press Enter to add a tag; each one is removable and every change is announced.",
    pattern: "Field + labelled chip list",
    accent: "#a7f3d0",
    status: "in-stock",
  },
  {
    slug: "quantity",
    category: "Inputs",
    name: "Quantity input",
    summary: "Minus, a real number field and plus, with the new amount and its limits said in words.",
    pattern: "Number input + buttons",
    accent: "#fde68a",
    status: "in-stock",
  },
  {
    slug: "currency-input",
    category: "Inputs",
    name: "Currency input",
    summary: "Type an amount freely; it is tidied on leaving and sent to your server as a plain number.",
    pattern: "Text input + hidden value",
    accent: "#bbf7d0",
    status: "in-stock",
  },
  {
    slug: "phone-input",
    category: "Inputs",
    name: "Phone input",
    summary: "Country code beside the number, digits grouped the local way, one value for your server.",
    pattern: "Select + tel input",
    accent: "#bae6fd",
    status: "in-stock",
  },
  {
    slug: "inline-edit",
    category: "Inputs",
    name: "Inline edit",
    summary: "A value that turns into a field on click, with Enter to save, Escape to cancel, and focus kept.",
    pattern: "Button to field, with focus moves",
    accent: "#ddd6fe",
    status: "in-stock",
  },
  {
    slug: "color-picker",
    category: "Inputs",
    name: "Colour picker",
    summary: "Named swatches as one radio group, plus the browser's own picker for anything else.",
    pattern: "Radio group + native colour input",
    accent: "#fbcfe8",
    status: "in-stock",
  },
  {
    slug: "back-to-top",
    category: "Navigation",
    name: "Back to top button",
    summary: "Appears once you have scrolled, and moves focus to the top as well as the page.",
    pattern: "Button + focus move",
    accent: "#c7d2fe",
    status: "in-stock",
  },
  {
    slug: "reading-progress",
    category: "Navigation",
    name: "Reading progress bar",
    summary: "A progress bar for how far you have read, and a contents list that marks the section you are in.",
    pattern: "role=progressbar + aria-current",
    accent: "#99f6e4",
    status: "in-stock",
  },
  {
    slug: "language-switcher",
    category: "Navigation",
    name: "Language switcher",
    summary: "Languages written in their own language, as real links carrying lang and hreflang.",
    pattern: "Disclosure + links",
    accent: "#fca5a5",
    status: "in-stock",
  },
  {
    slug: "filter-bar",
    category: "Inputs",
    name: "Filter bar",
    summary: "Chips that are real toggles, removable pills for what is on, and one status line that sums it up.",
    pattern: "Toggle buttons + status",
    accent: "#5eead4",
    status: "in-stock",
  },
  {
    slug: "data-grid",
    category: "Content",
    name: "Data grid",
    summary: "A table with a header that stays put, sortable columns reporting aria-sort, and columns you can resize by arrow key.",
    pattern: "Table + sort + resize",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "kanban",
    category: "Content",
    name: "Kanban board",
    summary: "Cards that move by button as well as by drag, with focus and announcements following them.",
    pattern: "Board + move buttons",
    accent: "#c4b5fd",
    status: "in-stock",
  },
  {
    slug: "confirm-dialog",
    category: "Overlays",
    name: "Confirm dialog",
    summary: "The dangerous button stays off until the words are typed exactly, with the reason said out loud.",
    pattern: "Modal dialog + guard",
    accent: "#fca5a5",
    status: "in-stock",
  },
  {
    slug: "session-timeout",
    category: "Overlays",
    name: "Session timeout",
    summary: "An idle warning that counts down, speaks at the marks worth hearing, and treats Escape as staying.",
    pattern: "Timed modal dialog",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "unsaved-changes",
    category: "Feedback",
    name: "Unsaved changes guard",
    summary: "Asks before leaving only while there is something to lose, in the page and on closing the tab.",
    pattern: "Dirty state + dialog",
    accent: "#fdba74",
    status: "in-stock",
  },
  {
    slug: "offline-banner",
    category: "Feedback",
    name: "Offline banner",
    summary: "Says the connection went and what is being kept, politely, with a retry that actually re-checks.",
    pattern: "Network status region",
    accent: "#fcd34d",
    status: "in-stock",
  },
  {
    slug: "shortcut-help",
    category: "Overlays",
    name: "Keyboard shortcuts dialog",
    summary: "One key brings up the shortcut sheet — unless you are typing, where ? is just a question mark.",
    pattern: "Modal dialog + hotkey",
    accent: "#5eead4",
    status: "in-stock",
  },
  {
    slug: "pricing-table",
    category: "Page sections",
    name: "Pricing table",
    summary: "Plans with a monthly/yearly radio group, a badge in words on the highlighted plan, and prices exactly as you write them.",
    pattern: "Radio group + cards",
    accent: "#5eead4",
    status: "in-stock",
  },
  {
    slug: "stats-tiles",
    category: "Content",
    name: "Stat cards",
    summary: "KPI tiles as a description list, with the change written in words so colour is never the only clue.",
    pattern: "Description list",
    accent: "#a7f3d0",
    status: "in-stock",
  },
  {
    slug: "timeline",
    category: "Content",
    name: "Activity timeline",
    summary: "An ordered list of what happened, with real time elements and the older entries behind one button.",
    pattern: "Ordered list + reveal",
    accent: "#c4b5fd",
    status: "in-stock",
  },
  {
    slug: "comment-thread",
    category: "Content",
    name: "Comment thread",
    summary: "Comments and replies as nested lists, a box that cannot post nothing, and a count that follows along.",
    pattern: "List + form",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "product-card",
    category: "Content",
    name: "Product card",
    summary: "Variant options as real radio groups, out-of-stock said in words, and an add button that waits for every choice.",
    pattern: "Fieldsets + guarded action",
    accent: "#fdba74",
    status: "in-stock",
  },
  {
    slug: "signature-pad",
    category: "Inputs",
    name: "Signature pad",
    summary: "Draw a signature with a pointer, or type the name instead — the alternative is the whole point.",
    pattern: "Canvas + typed alternative",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "code-block",
    category: "Content",
    name: "Code block with copy",
    summary: "Copy to clipboard with a real fallback when the clipboard is refused, plus line numbers that never get copied.",
    pattern: "Clipboard + status",
    accent: "#5eead4",
    status: "in-stock",
  },
  {
    slug: "toolbar",
    category: "Navigation",
    name: "Toolbar",
    summary: "One tab stop for the whole bar, arrow keys inside it, and toggles that report their state.",
    pattern: "APG toolbar",
    accent: "#c4b5fd",
    status: "in-stock",
  },
  {
    slug: "countdown",
    category: "Feedback",
    name: "Countdown",
    summary: "Digits that tick every second without being read out every second — the announcement follows the coarse reading.",
    pattern: "Timer + polite status",
    accent: "#fcd34d",
    status: "in-stock",
  },
  {
    slug: "slot-picker",
    category: "Inputs",
    name: "Time slot picker",
    summary: "One radio group across every day, taken slots said in words, and announcements that carry the day as well as the time.",
    pattern: "Grouped radio group",
    accent: "#a7f3d0",
    status: "in-stock",
  },
  {
    slug: "wizard",
    category: "Navigation",
    name: "Multi-step wizard",
    summary: "One step at a time, focus moved to each step's heading, and a needed field you cannot walk past.",
    pattern: "Steps + per-step validation",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "checkbox-group",
    category: "Inputs",
    name: "Checkbox group",
    summary: "Boxes under one question, an everything box that shows the mixed state, and a count said politely.",
    pattern: "Fieldset + checkboxes",
    accent: "#93c5fd",
    status: "in-stock",
  },
  {
    slug: "radio-cards",
    category: "Inputs",
    name: "Radio cards",
    summary: "Choices as cards that are still real radios: one tab stop, arrow keys, and unavailable said in words.",
    pattern: "Fieldset + radio cards",
    accent: "#5eead4",
    status: "in-stock",
  },
  {
    slug: "textarea-counter",
    category: "Inputs",
    name: "Textarea with counter",
    summary: "A character count that is read out at the marks that matter, not on every keystroke.",
    pattern: "Textarea + polite counter",
    accent: "#fdba74",
    status: "in-stock",
  },
  {
    slug: "select-field",
    category: "Inputs",
    name: "Select field",
    summary: "The humble native select done properly: real label, optgroups, and an error that takes focus back.",
    pattern: "Native select + validation",
    accent: "#c4b5fd",
    status: "in-stock",
  },
];

/** Parts that span the whole width, so both preview frames show them without page padding. */
export const fullBleed = ["cta", "header", "footer", "mega-menu"];

export const inStock = parts.filter((part) => part.status === "in-stock");
export const partBySlug = (slug: string) => parts.find((part) => part.slug === slug)!;
