import type { ConfigOf, Schema } from "@/lib/schema";
import type { FormConfig } from "./react/form";

export const formSchema = [
  { key: "title", label: "Title", description: "Heading above the fields.", group: "Content", type: "text", default: "Send us a message", maxLength: 80 },
  { key: "submitText", label: "Submit button text", description: "Name the action.", group: "Content", type: "text", default: "Send message", maxLength: 40 },
  {
    key: "successMessage",
    label: "Success message",
    description: "Shown and announced once the form is sent.",
    group: "Content",
    type: "text",
    default: "Thanks. Your message has been sent.",
    maxLength: 160,
  },
  { key: "nameLabel", label: "Name field label", description: "Always shown, always required.", group: "Content", type: "text", default: "Full name", maxLength: 40 },
  { key: "emailLabel", label: "Email field label", description: "Always shown, always required.", group: "Content", type: "text", default: "Email address", maxLength: 40 },
  {
    key: "validateOn",
    label: "Check answers",
    description: "As each field is left, or only when the form is sent.",
    group: "Behaviour",
    type: "select",
    default: "blur",
    options: ["blur", "submit"],
  },
  {
    key: "messageMinLength",
    label: "Shortest message",
    description: "Characters required in the message. 0 makes it optional.",
    group: "Behaviour",
    type: "number",
    default: 20,
    min: 0,
    max: 500,
    step: 10,
  },
  {
    key: "phoneRequired",
    label: "Phone is required",
    description: "Off means the phone field is marked optional.",
    group: "Behaviour",
    type: "boolean",
    default: false,
    dependsOn: { key: "phoneField", equals: true },
  },
  {
    key: "phoneField",
    label: "Phone field",
    description: "Adds a phone number field with its own format check.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "phoneLabel",
    label: "Phone field label",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "Phone number",
    maxLength: 40,
    dependsOn: { key: "phoneField", equals: true },
  },
  { key: "messageField", label: "Message field", description: "A multi-line box for the enquiry.", group: "Add-ons", type: "boolean", default: true },
  {
    key: "messageLabel",
    label: "Message field label",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "Message",
    maxLength: 40,
    dependsOn: { key: "messageField", equals: true },
  },
  {
    key: "consentField",
    label: "Consent checkbox",
    description: "A checkbox that must be ticked before sending.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "consentLabel",
    label: "Consent text",
    description: "What the visitor is agreeing to.",
    group: "Add-ons",
    type: "text",
    default: "I agree to be contacted about this enquiry",
    maxLength: 160,
    dependsOn: { key: "consentField", equals: true },
  },
  {
    key: "errorSummary",
    label: "Error summary",
    description: "Lists every problem at the top and moves focus there on submit.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "optionalMarker",
    label: "Mark optional fields",
    description: "Adds (optional) to fields that are not required.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "layout",
    label: "Columns",
    description: "Two columns side by side on wider screens.",
    group: "Style",
    type: "select",
    default: "two",
    options: ["one", "two"],
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The submit button and checkbox. Text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the fields and button.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof formSchema>, FormConfig> = true;
