import type { ConfigOf, Schema } from "@/lib/schema";
import type { FormConfig } from "./react/form";

export const formSchema = [
  {
    key: "title",
    label: "Title",
    description: "Heading above the fields.",
    group: "Content",
    type: "text",
    default: "Send us a message",
    maxLength: 80,
  },
  {
    key: "intro",
    label: "Intro",
    description: "One line under the heading. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "We answer every message within two working days.",
    maxLength: 200,
  },
  {
    key: "fields",
    label: "Fields",
    description:
      "One row per field. Type: text, email, tel, url, number, date, textarea, select or checkbox. Required: yes or no. Min and max are lengths for text, values for numbers, dates for dates.",
    group: "Content",
    type: "list",
    default: [
      { label: "Full name", type: "text", required: "yes", min: "2", max: "60", pattern: "", options: "", help: "" },
      { label: "Email address", type: "email", required: "yes", min: "", max: "", pattern: "", options: "", help: "" },
      { label: "Phone number", type: "tel", required: "no", min: "", max: "", pattern: "", options: "", help: "" },
      {
        label: "How can we help",
        type: "select",
        required: "yes",
        min: "",
        max: "",
        pattern: "",
        options: "New project, Support, Something else",
        help: "",
      },
      {
        label: "Message",
        type: "textarea",
        required: "yes",
        min: "20",
        max: "500",
        pattern: "",
        options: "",
        help: "Tell us what you need and when you need it.",
      },
      {
        label: "I agree to be contacted about this enquiry",
        type: "checkbox",
        required: "yes",
        min: "",
        max: "",
        pattern: "",
        options: "",
        help: "",
      },
    ],
    fields: [
      { key: "label", label: "Label", maxLength: 80 },
      { key: "type", label: "Type", maxLength: 12 },
      { key: "required", label: "Required (yes/no)", maxLength: 5 },
      { key: "min", label: "Min", maxLength: 12 },
      { key: "max", label: "Max", maxLength: 12 },
      { key: "pattern", label: "Pattern (regular expression)", maxLength: 120 },
      { key: "options", label: "Choices, separated by commas", maxLength: 300 },
      { key: "help", label: "Hint under the label", maxLength: 140 },
    ],
    maxItems: 14,
    itemLabel: "Field",
  },
  {
    key: "submitText",
    label: "Submit button text",
    description: "Name the action.",
    group: "Content",
    type: "text",
    default: "Send message",
    maxLength: 40,
  },
  {
    key: "successMessage",
    label: "Success message",
    description: "Shown and announced once the form is sent.",
    group: "Content",
    type: "text",
    default: "Thanks. Your message has been sent.",
    maxLength: 160,
  },
  {
    key: "validateOn",
    label: "Check answers",
    description: "As each field is left, as the visitor types, or only when the form is sent. A field that is already wrong is re-checked as it is corrected, whichever you pick.",
    group: "Behaviour",
    type: "select",
    default: "blur",
    options: ["blur", "input", "submit"],
  },
  {
    key: "marker",
    label: "Mark fields",
    description: "Say which fields are optional, which are required, or neither.",
    group: "Behaviour",
    type: "select",
    default: "optional",
    options: ["optional", "required", "none"],
  },
  {
    key: "errorSummary",
    label: "Error summary",
    description:
      "Off by default: each message sits under its own field. On, a list of every problem also appears at the top and takes focus on submit, as the GOV.UK Design System does.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "counter",
    label: "Characters remaining",
    description: "Counts down beside any text field that has a maximum, once there is something to count.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "layout",
    label: "Columns",
    description: "Two columns side by side on wider screens. Long fields always span both.",
    group: "Style",
    type: "select",
    default: "two",
    options: ["one", "two"],
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The submit button and focus rings. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the fields and the button.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
  {
    key: "checkboxText",
    label: "Box not ticked",
    description: "{label} is the field's label.",
    group: "Words",
    type: "text",
    default: "Select “{label}” to continue.",
    maxLength: 120,
  },
  {
    key: "missingText",
    label: "Empty field",
    description: "{name} is the label, starting lower case.",
    group: "Words",
    type: "text",
    default: "Enter {name}.",
    maxLength: 120,
  },
  {
    key: "selectMissingText",
    label: "Nothing chosen",
    description: "{name} is the label, starting lower case.",
    group: "Words",
    type: "text",
    default: "Select {name}.",
    maxLength: 120,
  },
  {
    key: "dateMissingText",
    label: "Empty date",
    description: "{name} is the label, starting lower case.",
    group: "Words",
    type: "text",
    default: "Enter {name}, for example 27 03 2026.",
    maxLength: 120,
  },
  {
    key: "emailText",
    label: "Not an email address",
    group: "Words",
    type: "text",
    default: "Enter an email address in the correct format, like name@example.com.",
    maxLength: 120,
  },
  {
    key: "telText",
    label: "Not a phone number",
    group: "Words",
    type: "text",
    default: "Enter a phone number using only digits, spaces, brackets, + or -, like +44 20 7946 0000.",
    maxLength: 120,
  },
  {
    key: "urlText",
    label: "Not a web address",
    group: "Words",
    type: "text",
    default: "Enter a web address in the correct format, like https://example.com.",
    maxLength: 120,
  },
  {
    key: "notInListText",
    label: "Not in the list",
    description: "{name} is the label, starting lower case.",
    group: "Words",
    type: "text",
    default: "Select {name} from the list.",
    maxLength: 120,
  },
  {
    key: "notNumberText",
    label: "Not a number",
    description: "{label} is the field's label.",
    group: "Words",
    type: "text",
    default: "{label} must be a number.",
    maxLength: 120,
  },
  {
    key: "tooSmallText",
    label: "Number too small",
    group: "Words",
    type: "text",
    default: "{label} must be {min} or more.",
    maxLength: 120,
  },
  {
    key: "tooBigText",
    label: "Number too big",
    group: "Words",
    type: "text",
    default: "{label} must be {max} or less.",
    maxLength: 120,
  },
  {
    key: "tooEarlyText",
    label: "Date too early",
    group: "Words",
    type: "text",
    default: "{label} must be {min} or later.",
    maxLength: 120,
  },
  {
    key: "tooLateText",
    label: "Date too late",
    group: "Words",
    type: "text",
    default: "{label} must be {max} or earlier.",
    maxLength: 120,
  },
  {
    key: "tooShortText",
    label: "Too short",
    description: "{count} is how many were typed.",
    group: "Words",
    type: "text",
    default: "{label} must be at least {min} characters. You have entered {count}.",
    maxLength: 120,
  },
  {
    key: "tooLongText",
    label: "Too long",
    description: "{count} is how many were typed.",
    group: "Words",
    type: "text",
    default: "{label} must be {max} characters or fewer. You have entered {count}.",
    maxLength: 120,
  },
  {
    key: "formatHelpText",
    label: "Wrong format, with help",
    description: "{help} is the field's help text.",
    group: "Words",
    type: "text",
    default: "Enter {name} in the format described: {help}",
    maxLength: 120,
  },
  {
    key: "formatText",
    label: "Wrong format",
    group: "Words",
    type: "text",
    default: "Enter {name} in the requested format.",
    maxLength: 120,
  },
  {
    key: "summaryTitle",
    label: "Error summary title",
    group: "Words",
    type: "text",
    default: "There is a problem",
    maxLength: 120,
  },
  {
    key: "errorPrefix",
    label: "Before an error",
    description: "Read out before each error, not shown.",
    group: "Words",
    type: "text",
    default: "Error:",
    maxLength: 120,
  },
  {
    key: "optionalText",
    label: "Optional marker",
    group: "Words",
    type: "text",
    default: "(optional)",
    maxLength: 120,
  },
  {
    key: "requiredText",
    label: "Required marker",
    group: "Words",
    type: "text",
    default: "(required)",
    maxLength: 120,
  },
  {
    key: "chooseOneText",
    label: "Empty choice",
    description: "The first entry of a drop-down.",
    group: "Words",
    type: "text",
    default: "Choose one",
    maxLength: 120,
  },
  {
    key: "remainingText",
    label: "Characters left",
    group: "Words",
    type: "text",
    default: "{count} characters remaining",
    maxLength: 120,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof formSchema>, FormConfig> = true;
