import type { ConfigOf, Schema } from "@/lib/schema";
import type { FormConfig } from "./react/form";

export const formSchema = [
  {
    key: "title",
    label: "Title",
    description: "Heading above the fields.",
    group: "Content",
    type: "text",
    default: "Send us a message",
    maxLength: 80,
  },
  {
    key: "intro",
    label: "Intro",
    description: "One line under the heading. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "We answer every message within two working days.",
    maxLength: 200,
  },
  {
    key: "fields",
    label: "Fields",
    description:
      "One row per field. Type: text, email, tel, url, number, date, textarea, select or checkbox. Required: yes or no. Min and max are lengths for text, values for numbers, dates for dates.",
    group: "Content",
    type: "list",
    default: [
      { label: "Full name", type: "text", required: "yes", min: "2", max: "60", pattern: "", options: "", help: "" },
      { label: "Email address", type: "email", required: "yes", min: "", max: "", pattern: "", options: "", help: "" },
      { label: "Phone number", type: "tel", required: "no", min: "", max: "", pattern: "", options: "", help: "" },
      {
        label: "How can we help",
        type: "select",
        required: "yes",
        min: "",
        max: "",
        pattern: "",
        options: "New project, Support, Something else",
        help: "",
      },
      {
        label: "Message",
        type: "textarea",
        required: "yes",
        min: "20",
        max: "500",
        pattern: "",
        options: "",
        help: "Tell us what you need and when you need it.",
      },
      {
        label: "I agree to be contacted about this enquiry",
        type: "checkbox",
        required: "yes",
        min: "",
        max: "",
        pattern: "",
        options: "",
        help: "",
      },
    ],
    fields: [
      { key: "label", label: "Label", maxLength: 80 },
      { key: "type", label: "Type", maxLength: 12 },
      { key: "required", label: "Required (yes/no)", maxLength: 5 },
      { key: "min", label: "Min", maxLength: 12 },
      { key: "max", label: "Max", maxLength: 12 },
      { key: "pattern", label: "Pattern (regular expression)", maxLength: 120 },
      { key: "options", label: "Choices, separated by commas", maxLength: 300 },
      { key: "help", label: "Hint under the label", maxLength: 140 },
    ],
    maxItems: 14,
    itemLabel: "Field",
  },
  {
    key: "submitText",
    label: "Submit button text",
    description: "Name the action.",
    group: "Content",
    type: "text",
    default: "Send message",
    maxLength: 40,
  },
  {
    key: "successMessage",
    label: "Success message",
    description: "Shown and announced once the form is sent.",
    group: "Content",
    type: "text",
    default: "Thanks. Your message has been sent.",
    maxLength: 160,
  },
  {
    key: "validateOn",
    label: "Check answers",
    description: "As each field is left, as the visitor types, or only when the form is sent. A field that is already wrong is re-checked as it is corrected, whichever you pick.",
    group: "Behaviour",
    type: "select",
    default: "blur",
    options: ["blur", "input", "submit"],
  },
  {
    key: "marker",
    label: "Mark fields",
    description: "Say which fields are optional, which are required, or neither.",
    group: "Behaviour",
    type: "select",
    default: "optional",
    options: ["optional", "required", "none"],
  },
  {
    key: "errorSummary",
    label: "Error summary",
    description:
      "Off by default: each message sits under its own field. On, a list of every problem also appears at the top and takes focus on submit, as the GOV.UK Design System does.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "counter",
    label: "Characters remaining",
    description: "Counts down beside any text field that has a maximum, once there is something to count.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "layout",
    label: "Columns",
    description: "Two columns side by side on wider screens. Long fields always span both.",
    group: "Style",
    type: "select",
    default: "two",
    options: ["one", "two"],
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The submit button and focus rings. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the fields and the button.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof formSchema>, FormConfig> = true;
