import type { ConfigOf, Schema } from "@/lib/schema";
import type { PaginationConfig } from "./react/pagination";

export const paginationSchema = [
  {
    key: "label",
    label: "What is being paged",
    description: "Names this navigation, e.g. Orders. Screen readers read it as “Orders navigation”.",
    group: "Content",
    type: "text",
    default: "Orders",
    maxLength: 40,
  },
  {
    key: "prevText",
    label: "Previous text",
    description: "The button or link that goes back one page.",
    group: "Content",
    type: "text",
    default: "Previous",
    maxLength: 20,
  },
  {
    key: "nextText",
    label: "Next text",
    description: "The button or link that goes on one page.",
    group: "Content",
    type: "text",
    default: "Next",
    maxLength: 20,
  },
  {
    key: "totalPages",
    label: "Pages",
    description: "How many pages there are in total.",
    group: "Behaviour",
    type: "number",
    default: 12,
    min: 1,
    max: 200,
  },
  {
    key: "startPage",
    label: "Starting page",
    description: "Which page is current when it loads, so you can see the middle of a long run.",
    group: "Behaviour",
    type: "number",
    default: 4,
    min: 1,
    max: 200,
  },
  {
    key: "siblings",
    label: "Pages either side",
    description: "How many page numbers sit either side of the current one before a gap.",
    group: "Behaviour",
    type: "number",
    default: 1,
    min: 0,
    max: 4,
  },
  {
    key: "hrefPattern",
    label: "Link pattern",
    description:
      "Set this to make each page a real link, e.g. /orders?page={page}. Leave it empty for buttons your own code handles.",
    group: "Behaviour",
    type: "text",
    default: "",
    maxLength: 200,
    format: "url",
  },
  {
    key: "look",
    label: "Look",
    description: "Numbered pages, or just previous and next with a count.",
    group: "Style",
    type: "select",
    default: "numbers",
    options: ["numbers", "compact"],
  },
  {
    key: "firstLast",
    label: "First and last",
    description: "Buttons that jump to either end.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "summary",
    label: "Page count",
    description: "Reads out “Page 4 of 12”, and says so again when the page changes.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The current page. Its text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of each control.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof paginationSchema>, PaginationConfig> = true;
