import type { ConfigOf, Schema } from "@/lib/schema";
import type { DatePickerConfig } from "./react/date-picker";

export const datePickerSchema = [
  {
    key: "label",
    label: "Label",
    description: "Text shown above the field.",
    group: "Content",
    type: "text",
    default: "Date",
    maxLength: 60,
  },
  {
    key: "name",
    label: "Form field name",
    description: "Name of the value sent when the form is submitted.",
    group: "Behaviour",
    type: "text",
    default: "date",
    maxLength: 40,
  },
  {
    key: "minDate",
    label: "Earliest date",
    description: "Days before this can't be picked.",
    group: "Behaviour",
    type: "date",
    default: "",
  },
  {
    key: "maxDate",
    label: "Latest date",
    description: "Days after this can't be picked.",
    group: "Behaviour",
    type: "date",
    default: "",
  },
  {
    key: "format",
    label: "Date format",
    description: "How dates are shown and typed.",
    group: "Behaviour",
    type: "select",
    default: "DD/MM/YYYY",
    options: ["DD/MM/YYYY", "MM/DD/YYYY", "YYYY/MM/DD", "YYYY-MM-DD"],
  },
  {
    key: "mode",
    label: "Selection",
    description: "Pick one date, or a start and end date.",
    group: "Behaviour",
    type: "select",
    default: "single",
    options: ["single", "range"],
  },
  {
    key: "weekStartsOn",
    label: "Week starts on",
    description: "First column of the calendar.",
    group: "Behaviour",
    type: "select",
    default: "monday",
    options: ["monday", "sunday"],
  },
  {
    key: "clearButton",
    label: "Clear button",
    description: "An × button that empties the field.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "todayButton",
    label: "Today button",
    description: "Jumps the calendar back to today.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "helperText",
    label: "Helper text",
    description: "A short hint under the field.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "helperTextContent",
    label: "Helper text content",
    description: "The hint itself.",
    group: "Add-ons",
    type: "text",
    default: "Select or type a date.",
    maxLength: 120,
    dependsOn: { key: "helperText", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "iosOnPhone",
    label: "iPhone look",
    description: "On iPhone and iPad: Apple's system font, iOS blue, bigger rows, and a sheet that slides up.",
    group: "Style",
    type: "boolean",
    default: true,
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "Selected days and focus rings. Text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the field, calendar and days.",
    group: "Style",
    type: "number",
    default: 6,
    min: 0,
    max: 16,
  },
  {
    key: "size",
    label: "Size",
    description: "Height of the field and the calendar cells.",
    group: "Style",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof datePickerSchema>, DatePickerConfig> = true;
