import type { ConfigOf, Schema } from "@/lib/schema";
import type { DatePickerConfig } from "./react/date-picker";

export const datePickerSchema = [
  {
    key: "label",
    label: "Label",
    description: "Text shown above the field.",
    group: "Content",
    type: "text",
    default: "Date",
    maxLength: 60,
  },
  {
    key: "name",
    label: "Form field name",
    description: "Name of the value sent when the form is submitted.",
    group: "Behaviour",
    type: "text",
    default: "date",
    maxLength: 40,
  },
  {
    key: "minDate",
    label: "Earliest date",
    description: "Days before this can't be picked.",
    group: "Behaviour",
    type: "date",
    default: "",
  },
  {
    key: "maxDate",
    label: "Latest date",
    description: "Days after this can't be picked.",
    group: "Behaviour",
    type: "date",
    default: "",
  },
  {
    key: "format",
    label: "Date format",
    description: "How dates are shown and typed.",
    group: "Behaviour",
    type: "select",
    default: "DD/MM/YYYY",
    options: ["DD/MM/YYYY", "MM/DD/YYYY", "YYYY/MM/DD", "YYYY-MM-DD"],
  },
  {
    key: "mode",
    label: "Selection",
    description: "Pick one date, or a start and end date.",
    group: "Behaviour",
    type: "select",
    default: "single",
    options: ["single", "range"],
  },
  {
    key: "weekStartsOn",
    label: "Week starts on",
    description: "First column of the calendar.",
    group: "Behaviour",
    type: "select",
    default: "monday",
    options: ["monday", "sunday"],
  },
  {
    key: "clearButton",
    label: "Clear button",
    description: "An × button that empties the field.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "todayButton",
    label: "Today button",
    description: "Jumps the calendar back to today.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "helperText",
    label: "Helper text",
    description: "A short hint under the field.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "helperTextContent",
    label: "Helper text content",
    description: "The hint itself.",
    group: "Add-ons",
    type: "text",
    default: "Select or type a date.",
    maxLength: 120,
    dependsOn: { key: "helperText", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "iosOnPhone",
    label: "iPhone look",
    description: "On iPhone and iPad: Apple's system font, iOS blue, bigger rows, and a sheet that slides up.",
    group: "Style",
    type: "boolean",
    default: true,
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "Selected days and focus rings. Text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the field, calendar and days.",
    group: "Style",
    type: "number",
    default: 6,
    min: 0,
    max: 16,
  },
  {
    key: "size",
    label: "Size",
    description: "Height of the field and the calendar cells.",
    group: "Style",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
  {
    key: "afterText",
    label: "Too early",
    description: "Said for a date before the earliest. {date} is the earliest.",
    group: "Words",
    type: "text",
    default: "Choose a date on or after {date}.",
    maxLength: 120,
  },
  {
    key: "beforeText",
    label: "Too late",
    description: "Said for a date after the latest. {date} is the latest.",
    group: "Words",
    type: "text",
    default: "Choose a date on or before {date}.",
    maxLength: 120,
  },
  {
    key: "formatHint",
    label: "Wrong format",
    description: "Said when the typing is not a date. {format} is the format.",
    group: "Words",
    type: "text",
    default: "Enter the date as {format}.",
    maxLength: 120,
  },
  {
    key: "badMonthText",
    label: "No such month",
    description: "{month} is what was typed.",
    group: "Words",
    type: "text",
    default: "{month} isn't a valid month. Use 01 to 12.",
    maxLength: 120,
  },
  {
    key: "badDayText",
    label: "No such day",
    description: "{day} is what was typed, {max} the month's last day.",
    group: "Words",
    type: "text",
    default: "Day {day} doesn't exist — that month has {max} days.",
    maxLength: 120,
  },
  {
    key: "rangeFormatText",
    label: "Wrong range format",
    description: "Said when a range is not two dates. {format} is the format.",
    group: "Words",
    type: "text",
    default: "Enter the dates as {format} – {format}.",
    maxLength: 120,
  },
  {
    key: "startErrorText",
    label: "Start date problem",
    description: "Puts the start date's problem in words. {error} is the problem.",
    group: "Words",
    type: "text",
    default: "Start date: {error}",
    maxLength: 160,
  },
  {
    key: "endErrorText",
    label: "End date problem",
    description: "Puts the end date's problem in words. {error} is the problem.",
    group: "Words",
    type: "text",
    default: "End date: {error}",
    maxLength: 160,
  },
  {
    key: "backwardsText",
    label: "Backwards range",
    description: "Said when the end is before the start.",
    group: "Words",
    type: "text",
    default: "The end date is before the start date.",
    maxLength: 120,
  },
  {
    key: "chooseDateLabel",
    label: "Calendar button",
    description: "Opens the calendar.",
    group: "Words",
    type: "text",
    default: "Choose date",
    maxLength: 40,
  },
  {
    key: "chooseDatesLabel",
    label: "Calendar button, range",
    description: "Opens the calendar to pick a range.",
    group: "Words",
    type: "text",
    default: "Choose dates",
    maxLength: 40,
  },
  {
    key: "clearDateLabel",
    label: "Clear button",
    description: "Empties the field.",
    group: "Words",
    type: "text",
    default: "Clear date",
    maxLength: 40,
  },
  {
    key: "clearDatesLabel",
    label: "Clear button, range",
    description: "Empties both dates.",
    group: "Words",
    type: "text",
    default: "Clear dates",
    maxLength: 40,
  },
  {
    key: "previousLabel",
    label: "Previous",
    description: "Read out for the left arrow. {step} is month, year or 12 years.",
    group: "Words",
    type: "text",
    default: "Previous {step}",
    maxLength: 40,
  },
  {
    key: "nextLabel",
    label: "Next",
    description: "Read out for the right arrow. {step} is month, year or 12 years.",
    group: "Words",
    type: "text",
    default: "Next {step}",
    maxLength: 40,
  },
  {
    key: "monthWord",
    label: "Month",
    description: "Used in Previous and Next on the days view.",
    group: "Words",
    type: "text",
    default: "month",
    maxLength: 20,
  },
  {
    key: "yearWord",
    label: "Year",
    description: "Used in Previous and Next on the months view.",
    group: "Words",
    type: "text",
    default: "year",
    maxLength: 20,
  },
  {
    key: "yearsWord",
    label: "Twelve years",
    description: "Used in Previous and Next on the years view.",
    group: "Words",
    type: "text",
    default: "12 years",
    maxLength: 20,
  },
  {
    key: "chooseYearLabel",
    label: "Years view",
    description: "Names the grid of years.",
    group: "Words",
    type: "text",
    default: "Choose year",
    maxLength: 40,
  },
  {
    key: "chooseMonthLabel",
    label: "Months view",
    description: "Names the grid of months.",
    group: "Words",
    type: "text",
    default: "Choose month",
    maxLength: 40,
  },
  {
    key: "endPromptText",
    label: "Pick the end",
    description: "Said after the start of a range is picked.",
    group: "Words",
    type: "text",
    default: "Now choose the end date.",
    maxLength: 80,
  },
  {
    key: "todayText",
    label: "Today",
    description: "The button that jumps to today.",
    group: "Words",
    type: "text",
    default: "Today",
    maxLength: 30,
  },
  {
    key: "headingDaysHint",
    label: "Heading button, calendar",
    description: "Read out after the month.",
    group: "Words",
    type: "text",
    default: "change month and year",
    maxLength: 160,
  },
  {
    key: "headingYearsHint",
    label: "Heading button, years",
    description: "Read out after the years.",
    group: "Words",
    type: "text",
    default: "back to calendar",
    maxLength: 160,
  },
  {
    key: "headingMonthsHint",
    label: "Heading button, months",
    description: "Read out after the year.",
    group: "Words",
    type: "text",
    default: "change year",
    maxLength: 160,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof datePickerSchema>, DatePickerConfig> = true;
