import type { ConfigOf, Schema } from "@/lib/schema";
import type { SidebarConfig } from "./react/sidebar";

export const sidebarSchema = [
  {
    key: "label",
    label: "Sidebar name",
    description: "Names this navigation for screen readers, e.g. Workspace.",
    group: "Content",
    type: "text",
    default: "Workspace",
    maxLength: 40,
  },
  {
    key: "items",
    label: "Links",
    description: "One row per link. Rows with the same section sit under the same heading.",
    group: "Content",
    type: "list",
    default: [
      { section: "Work", label: "Overview", href: "/overview", badge: "" },
      { section: "Work", label: "Orders", href: "/orders", badge: "12" },
      { section: "Work", label: "Customers", href: "/customers", badge: "" },
      { section: "Library", label: "Products", href: "/products", badge: "" },
      { section: "Library", label: "Collections", href: "/collections", badge: "3" },
      { section: "Settings", label: "Team", href: "/team", badge: "" },
      { section: "Settings", label: "Billing", href: "/billing", badge: "" },
    ],
    fields: [
      { key: "section", label: "Section", maxLength: 40 },
      { key: "label", label: "Text", maxLength: 40 },
      { key: "href", label: "Link", maxLength: 200, format: "url" },
      { key: "badge", label: "Count", maxLength: 6 },
    ],
    maxItems: 20,
    itemLabel: "Link",
  },
  {
    key: "activeHref",
    label: "Current page",
    description: "The link matching this address is marked as the page you are on.",
    group: "Behaviour",
    type: "text",
    default: "/orders",
    maxLength: 200,
    format: "url",
  },
  {
    key: "collapsible",
    label: "Collapsible sections",
    description: "Each section heading becomes a button that folds its links away.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  {
    key: "mobileBreakpoint",
    label: "Drawer below",
    description: "Under this width the sidebar becomes a button that opens a drawer.",
    group: "Behaviour",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
  {
    key: "toggleText",
    label: "Drawer button text",
    description: "What opens the drawer on a narrow screen.",
    group: "Content",
    type: "text",
    default: "Menu",
    maxLength: 20,
  },
  {
    key: "badges",
    label: "Counts",
    description: "Shows the count beside a link, with a word after it so it is not a bare number.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "width",
    label: "Width (px)",
    description: "How wide the sidebar is once there is room for it.",
    group: "Style",
    type: "number",
    default: 260,
    min: 180,
    max: 400,
    step: 10,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The current page and focus rings. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the panel and each link.",
    group: "Style",
    type: "number",
    default: 10,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof sidebarSchema>, SidebarConfig> = true;
