import type { ConfigOf, Schema } from "@/lib/schema";
import type { SliderConfig } from "./react/slider";

export const sliderSchema = [
  {
    key: "label",
    label: "Label",
    description: "What is being set.",
    group: "Content",
    type: "text",
    default: "Budget",
    maxLength: 60,
  },
  {
    key: "hint",
    label: "Hint",
    description: "Under the label. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Drag either end, or use the arrow keys.",
    maxLength: 160,
  },
  {
    key: "prefix",
    label: "Before the number",
    description: "A currency symbol, for example.",
    group: "Content",
    type: "text",
    default: "£",
    maxLength: 6,
  },
  {
    key: "suffix",
    label: "After the number",
    description: "A unit, such as km or %.",
    group: "Content",
    type: "text",
    default: "",
    maxLength: 6,
  },
  {
    key: "mode",
    label: "Kind",
    description: "One value, or a range with a lowest and a highest.",
    group: "Behaviour",
    type: "select",
    default: "range",
    options: ["single", "range"],
  },
  {
    key: "min",
    label: "Lowest",
    description: "The bottom of the scale.",
    group: "Behaviour",
    type: "number",
    default: 0,
    min: 0,
    max: 1000,
  },
  {
    key: "max",
    label: "Highest",
    description: "The top of the scale.",
    group: "Behaviour",
    type: "number",
    default: 200,
    min: 1,
    max: 10000,
  },
  {
    key: "step",
    label: "Step",
    description: "How far one arrow key press moves it.",
    group: "Behaviour",
    type: "number",
    default: 10,
    min: 1,
    max: 100,
  },
  {
    key: "startValue",
    label: "Starting value",
    description: "For one value. Ignored for a range.",
    group: "Behaviour",
    type: "number",
    default: 80,
    min: 0,
    max: 10000,
  },
  {
    key: "startLower",
    label: "Starting lowest",
    description: "For a range.",
    group: "Behaviour",
    type: "number",
    default: 40,
    min: 0,
    max: 10000,
  },
  {
    key: "startUpper",
    label: "Starting highest",
    description: "For a range.",
    group: "Behaviour",
    type: "number",
    default: 140,
    min: 0,
    max: 10000,
  },
  {
    key: "showValue",
    label: "Show the value",
    description: "Beside the label, and announced as it changes.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The filled part of the track and the handles.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof sliderSchema>, SliderConfig> = true;
