import type { ConfigOf, Schema } from "@/lib/schema";
import type { TimePickerConfig } from "./react/time-picker";

export const timePickerSchema = [
  {
    key: "label",
    label: "Label",
    description: "Names the field. Also used to name the list of times.",
    group: "Content",
    type: "text",
    default: "Start time",
    maxLength: 60,
  },
  {
    key: "hint",
    label: "Hint",
    description: "Under the label. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Type a time, or pick one from the list.",
    maxLength: 160,
  },
  {
    key: "format",
    label: "Clock",
    description: "24-hour (14:30) or 12-hour (2:30 pm). Either way, both can be typed.",
    group: "Behaviour",
    type: "select",
    default: "24h",
    options: ["24h", "12h"],
  },
  {
    key: "interval",
    label: "Minutes between listed times",
    description: "Only changes the list. Any time in range can still be typed.",
    group: "Behaviour",
    type: "select",
    default: "30",
    options: ["5", "10", "15", "30", "60"],
  },
  {
    key: "earliest",
    label: "Earliest time",
    description: "24-hour, like 08:00. Earlier times are refused with a message.",
    group: "Behaviour",
    type: "text",
    default: "08:00",
    maxLength: 5,
  },
  {
    key: "latest",
    label: "Latest time",
    description: "24-hour, like 18:00.",
    group: "Behaviour",
    type: "text",
    default: "18:00",
    maxLength: 5,
  },
  {
    key: "startValue",
    label: "Starting time",
    description: "24-hour. Leave empty to start blank.",
    group: "Behaviour",
    type: "text",
    default: "",
    maxLength: 5,
  },
  {
    key: "name",
    label: "Form field name",
    description: "Submits the time as HH:MM (24-hour) under this name. Leave empty to leave it out.",
    group: "Add-ons",
    type: "text",
    default: "start-time",
    maxLength: 40,
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The highlighted time in the list and the focus ring.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "showOptionsLabel",
    label: "Open button",
    description: "Read out on the button that opens the list. {name} is the label.",
    group: "Words",
    type: "text",
    default: "Show {name} options",
    maxLength: 80,
  },
  {
    key: "format24Text",
    label: "Format, 24-hour",
    description: "Read out with the field.",
    group: "Words",
    type: "text",
    default: "Format: 24-hour, for example 14:30.",
    maxLength: 80,
  },
  {
    key: "format12Text",
    label: "Format, 12-hour",
    description: "Read out with the field.",
    group: "Words",
    type: "text",
    default: "Format: 12-hour, for example 2:30 pm.",
    maxLength: 80,
  },
  {
    key: "placeholder24",
    label: "Placeholder, 24-hour",
    group: "Words",
    type: "text",
    default: "hh:mm",
    maxLength: 20,
  },
  {
    key: "placeholder12",
    label: "Placeholder, 12-hour",
    group: "Words",
    type: "text",
    default: "h:mm am",
    maxLength: 20,
  },
  {
    key: "badTimeText",
    label: "Not a time",
    description: "{example} is a time in the chosen format.",
    group: "Words",
    type: "text",
    default: "Enter a time like {example}.",
    maxLength: 80,
  },
  {
    key: "outOfRangeText",
    label: "Outside the hours",
    group: "Words",
    type: "text",
    default: "Choose a time between {earliest} and {latest}.",
    maxLength: 80,
  },
  {
    key: "timeOneText",
    label: "One time listed",
    description: "Announced as the list filters.",
    group: "Words",
    type: "text",
    default: "{count} time listed.",
    maxLength: 80,
  },
  {
    key: "timesText",
    label: "Several times listed",
    description: "Announced as the list filters.",
    group: "Words",
    type: "text",
    default: "{count} times listed.",
    maxLength: 80,
  },
  {
    key: "noneListedText",
    label: "None listed",
    description: "Announced when no listed time matches.",
    group: "Words",
    type: "text",
    default: "No listed time matches; you can still type one.",
    maxLength: 80,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof timePickerSchema>, TimePickerConfig> = true;
