import type { ConfigOf, Schema } from "@/lib/schema";
import type { MegaMenuConfig } from "./react/mega-menu";

export const megaMenuSchema = [
  {
    key: "logoText",
    label: "Logo text",
    description: "Your name or brand, at the start of the bar.",
    group: "Content",
    type: "text",
    default: "Northwind",
    maxLength: 40,
  },
  {
    key: "label",
    label: "Menu name",
    description: "Names this navigation for screen readers, e.g. Main.",
    group: "Content",
    type: "text",
    default: "Main",
    maxLength: 40,
  },
  {
    key: "items",
    label: "Panel links",
    description: "One row per link. Rows with the same menu open together; rows with the same group share a column.",
    group: "Content",
    type: "list",
    default: [
      { menu: "Products", group: "Build", label: "Editor", href: "/editor", description: "Set options and see the result" },
      { menu: "Products", group: "Build", label: "Registry", href: "/registry", description: "Install by URL" },
      { menu: "Products", group: "Ship", label: "Exports", href: "/exports", description: "React and plain HTML" },
      { menu: "Products", group: "Ship", label: "Tests", href: "/tests", description: "Keyboard and axe on every output" },
      {
        menu: "Solutions",
        group: "By team",
        label: "Design systems",
        href: "/design-systems",
        description: "One set of parts for everyone",
      },
      { menu: "Solutions", group: "By team", label: "Agencies", href: "/agencies", description: "Hand clients code they own" },
      {
        menu: "Solutions",
        group: "By need",
        label: "Accessibility",
        href: "/accessibility",
        description: "Patterns that pass an audit",
      },
    ],
    fields: [
      { key: "menu", label: "Menu", maxLength: 40 },
      { key: "group", label: "Column heading", maxLength: 40 },
      { key: "label", label: "Link text", maxLength: 40 },
      { key: "href", label: "Link", maxLength: 200, format: "url" },
      { key: "description", label: "Description", maxLength: 80 },
    ],
    maxItems: 24,
    itemLabel: "Link",
  },
  {
    key: "links",
    label: "Plain links",
    description: "Links in the bar that open nothing, after the menus.",
    group: "Content",
    type: "list",
    default: [
      { label: "Pricing", href: "/pricing" },
      { label: "Docs", href: "/docs" },
    ],
    fields: [
      { key: "label", label: "Text", maxLength: 40 },
      { key: "href", label: "Link", maxLength: 200, format: "url" },
    ],
    maxItems: 6,
    itemLabel: "Link",
  },
  {
    key: "openOn",
    label: "Open a panel on",
    description: "Click is the safer default; hover also opens as the pointer arrives.",
    group: "Behaviour",
    type: "select",
    default: "click",
    options: ["click", "hover"],
  },
  {
    key: "panel",
    label: "Panel width",
    description: "Aligned under its button, or the full width of the bar.",
    group: "Behaviour",
    type: "select",
    default: "aligned",
    options: ["aligned", "full"],
  },
  {
    key: "descriptions",
    label: "Link descriptions",
    description: "Shows the description under each link.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "ctaButton",
    label: "Call to action",
    description: "A button at the end of the bar.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "ctaText",
    label: "Button text",
    description: "Name the action.",
    group: "Add-ons",
    type: "text",
    default: "Start free",
    maxLength: 40,
    dependsOn: { key: "ctaButton", equals: true },
  },
  {
    key: "ctaHref",
    label: "Button link",
    description: "Where it goes.",
    group: "Add-ons",
    type: "text",
    default: "/signup",
    maxLength: 200,
    format: "url",
    dependsOn: { key: "ctaButton", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The call to action and focus rings. Contrast-corrected before it is used as text.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "columns",
    label: "Columns",
    description: "How many columns a panel uses once there is room.",
    group: "Style",
    type: "select",
    default: "2",
    options: ["2", "3", "4"],
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the panel, buttons and links.",
    group: "Style",
    type: "number",
    default: 10,
    min: 0,
    max: 24,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof megaMenuSchema>, MegaMenuConfig> = true;
