import type { ConfigOf, Schema } from "@/lib/schema";
import type { CountdownConfig } from "./react/countdown";

export const countdownSchema = [
  { key: "label", label: "Label", group: "Content", type: "text", default: "Doors open in", maxLength: 60 },
  {
    key: "target",
    label: "Counts down to",
    description: "The moment it ends, as 2026-12-24T18:00. Read in the visitor's own time zone.",
    group: "Content",
    type: "text",
    default: "2026-12-24T18:00",
    maxLength: 30,
  },
  { key: "finishedText", label: "When it ends", group: "Content", type: "text", default: "Doors are open.", maxLength: 80 },
  { key: "showSeconds", label: "Show seconds", group: "Style", type: "boolean", default: true },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  { key: "accentColor", label: "Accent colour", group: "Style", type: "color", default: "#b45309" },
  {
    key: "dayOne",
    label: "One day",
    description: "{count} is 1.",
    group: "Words",
    type: "text",
    default: "{count} day",
    maxLength: 30,
  },
  {
    key: "dayMany",
    label: "Days",
    description: "{count} is the number.",
    group: "Words",
    type: "text",
    default: "{count} days",
    maxLength: 30,
  },
  {
    key: "hourOne",
    label: "One hour",
    description: "{count} is 1.",
    group: "Words",
    type: "text",
    default: "{count} hour",
    maxLength: 30,
  },
  {
    key: "hourMany",
    label: "Hours",
    description: "{count} is the number.",
    group: "Words",
    type: "text",
    default: "{count} hours",
    maxLength: 30,
  },
  {
    key: "minuteOne",
    label: "One minute",
    description: "{count} is 1.",
    group: "Words",
    type: "text",
    default: "{count} minute",
    maxLength: 30,
  },
  {
    key: "minuteMany",
    label: "Minutes",
    description: "{count} is the number.",
    group: "Words",
    type: "text",
    default: "{count} minutes",
    maxLength: 30,
  },
  {
    key: "secondOne",
    label: "One second",
    description: "{count} is 1.",
    group: "Words",
    type: "text",
    default: "{count} second",
    maxLength: 30,
  },
  {
    key: "secondMany",
    label: "Seconds",
    description: "{count} is the number.",
    group: "Words",
    type: "text",
    default: "{count} seconds",
    maxLength: 30,
  },
  {
    key: "twoText",
    label: "Two units left",
    description: "Said with days or hours to go. {first} and {second} are filled in.",
    group: "Words",
    type: "text",
    default: "{first} and {second} left",
    maxLength: 60,
  },
  {
    key: "oneText",
    label: "One unit left",
    description: "Said in the last hour. {first} is filled in.",
    group: "Words",
    type: "text",
    default: "{first} left",
    maxLength: 40,
  },
  {
    key: "daysLabel",
    label: "Days box",
    description: "Under the days number.",
    group: "Words",
    type: "text",
    default: "days",
    maxLength: 20,
  },
  {
    key: "hoursLabel",
    label: "Hours box",
    description: "Under the hours number.",
    group: "Words",
    type: "text",
    default: "hours",
    maxLength: 20,
  },
  {
    key: "minutesLabel",
    label: "Minutes box",
    description: "Under the minutes number.",
    group: "Words",
    type: "text",
    default: "minutes",
    maxLength: 20,
  },
  {
    key: "secondsLabel",
    label: "Seconds box",
    description: "Under the seconds number.",
    group: "Words",
    type: "text",
    default: "seconds",
    maxLength: 20,
  },
  {
    key: "waitingText",
    label: "Working it out",
    description: "Shown for a moment before the browser has the time.",
    group: "Words",
    type: "text",
    default: "Working out the time left…",
    maxLength: 60,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof countdownSchema>, CountdownConfig> = true;
