import type { ConfigOf, Schema } from "@/lib/schema";
import type { DrawerConfig } from "./react/drawer";

export const drawerSchema = [
  {
    key: "triggerText",
    label: "Button text",
    description: "The button that opens the drawer.",
    group: "Content",
    type: "text",
    default: "Filters",
    maxLength: 40,
  },
  {
    key: "title",
    label: "Title",
    description: "Names the drawer; read out when it opens.",
    group: "Content",
    type: "text",
    default: "Filter results",
    maxLength: 60,
  },
  {
    key: "body",
    label: "Intro",
    description: "Under the title. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Pick what to show. Nothing changes until you press Show results.",
    maxLength: 200,
  },
  {
    key: "options",
    label: "Choices",
    description: "Example content: one checkbox each. Replace with your own in the code.",
    group: "Content",
    type: "list",
    default: [{ label: "In stock" }, { label: "On sale" }, { label: "Free delivery" }, { label: "Rated 4 stars and up" }],
    fields: [{ key: "label", label: "Text", maxLength: 60 }],
    maxItems: 20,
    itemLabel: "Choice",
  },
  {
    key: "primaryText",
    label: "Main button",
    group: "Content",
    type: "text",
    default: "Show results",
    maxLength: 30,
  },
  {
    key: "secondaryButton",
    label: "Second button",
    description: "Clears the choices without closing.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "secondaryText",
    label: "Second button text",
    group: "Content",
    type: "text",
    default: "Clear all",
    maxLength: 30,
    dependsOn: { key: "secondaryButton", equals: true },
  },
  {
    key: "side",
    label: "Side",
    description: "Which edge it slides in from. Bottom works well on phones.",
    group: "Behaviour",
    type: "select",
    default: "right",
    options: ["right", "left", "bottom"],
  },
  {
    key: "closeOnBackdrop",
    label: "Close on outside click",
    description: "A click on the dimmed page closes it. Escape always does.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  {
    key: "swipeToClose",
    label: "Swipe to close",
    description: "On touch screens, swiping toward its edge closes it.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  {
    key: "size",
    label: "Size",
    description: "Width from the side, or height from the bottom.",
    group: "Style",
    type: "select",
    default: "md",
    options: ["sm", "md", "lg"],
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The main button, checkboxes and the focus ring.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof drawerSchema>, DrawerConfig> = true;
