import type { ConfigOf, Schema } from "@/lib/schema";
import type { CtaConfig } from "./react/cta";

export const ctaSchema = [
  {
    key: "heading",
    label: "Heading",
    description: "The one line that has to land.",
    group: "Content",
    type: "text",
    default: "Ready to start your project?",
    maxLength: 120,
  },
  {
    key: "body",
    label: "Supporting text",
    description: "One or two sentences under the heading. Leave empty to drop it.",
    group: "Content",
    type: "text",
    default: "Tell us what you need and we will come back to you within two working days.",
    maxLength: 300,
  },
  {
    key: "primaryText",
    label: "Button text",
    description: "Name the action, not the click.",
    group: "Content",
    type: "text",
    default: "Get in touch",
    maxLength: 40,
  },
  {
    key: "primaryHref",
    label: "Button link",
    description: "Where the button goes.",
    group: "Content",
    type: "text",
    default: "/contact",
    maxLength: 200,
    format: "url",
  },
  {
    key: "headingLevel",
    label: "Heading level",
    description: "Use H2 inside a page that already has an H1.",
    group: "Behaviour",
    type: "select",
    default: "h2",
    options: ["h2", "h3"],
  },
  {
    key: "layout",
    label: "Alignment",
    description: "Centred, or aligned to the start of the line.",
    group: "Behaviour",
    type: "select",
    default: "centered",
    options: ["centered", "left"],
  },
  {
    key: "secondaryButton",
    label: "Second button",
    description: "A quieter alternative next to the main action.",
    group: "Add-ons",
    type: "boolean",
    default: true,
  },
  {
    key: "secondaryText",
    label: "Second button text",
    description: "Its label.",
    group: "Add-ons",
    type: "text",
    default: "See our work",
    maxLength: 40,
    dependsOn: { key: "secondaryButton", equals: true },
  },
  {
    key: "secondaryHref",
    label: "Second button link",
    description: "Where it goes.",
    group: "Add-ons",
    type: "text",
    default: "/work",
    maxLength: 200,
    format: "url",
    dependsOn: { key: "secondaryButton", equals: true },
  },
  {
    key: "note",
    label: "Note under the buttons",
    description: "Small print such as response times or terms.",
    group: "Add-ons",
    type: "boolean",
    default: false,
  },
  {
    key: "noteText",
    label: "Note text",
    description: "Keep it to one line.",
    group: "Add-ons",
    type: "text",
    default: "No commitment. We reply to every message.",
    maxLength: 120,
    dependsOn: { key: "note", equals: true },
  },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  {
    key: "accentColor",
    label: "Accent colour",
    description: "The main button. Its text colour adjusts for contrast.",
    group: "Style",
    type: "color",
    default: "#2563eb",
  },
  {
    key: "radius",
    label: "Corner radius (px)",
    description: "Roundness of the buttons.",
    group: "Style",
    type: "number",
    default: 8,
    min: 0,
    max: 24,
  },
  {
    key: "spacing",
    label: "Vertical space",
    description: "How much room the section takes.",
    group: "Style",
    type: "select",
    default: "regular",
    options: ["compact", "regular", "spacious"],
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof ctaSchema>, CtaConfig> = true;
