import type { ConfigOf, Schema } from "@/lib/schema";
import type { DataGridConfig } from "./react/data-grid";

export const dataGridSchema = [
  { key: "caption", label: "Caption", description: "What the table is of. Screen readers read it first.", group: "Content", type: "text", default: "Documents", maxLength: 60 },
  {
    key: "rows",
    label: "Rows",
    group: "Content",
    type: "list",
    default: [
      { name: "Anchor plan", owner: "Priya", status: "In review", updated: "4 Mar 2026" },
      { name: "Ballast notes", owner: "Sam", status: "Draft", updated: "2 Mar 2026" },
      { name: "Cargo manifest", owner: "Ade", status: "Signed off", updated: "28 Feb 2026" },
      { name: "Deck survey", owner: "Marta", status: "In review", updated: "26 Feb 2026" },
      { name: "Engine log", owner: "Sam", status: "Draft", updated: "21 Feb 2026" },
      { name: "Fuel report", owner: "Priya", status: "Signed off", updated: "19 Feb 2026" },
      { name: "Galley order", owner: "Ade", status: "Draft", updated: "14 Feb 2026" },
      { name: "Hull check", owner: "Marta", status: "Signed off", updated: "11 Feb 2026" },
    ],
    fields: [
      { key: "name", label: "Name", maxLength: 60 },
      { key: "owner", label: "Owner", maxLength: 40 },
      { key: "status", label: "Status", maxLength: 40 },
      { key: "updated", label: "Updated", maxLength: 40 },
    ],
    maxItems: 40,
    itemLabel: "Row",
  },
  {
    key: "stickyHeader",
    label: "Header stays put",
    description: "The header row stays visible while the rows scroll under it.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  { key: "sortable", label: "Sortable columns", description: "Each header becomes a button and reports aria-sort.", group: "Behaviour", type: "boolean", default: true },
  {
    key: "resizable",
    label: "Resizable columns",
    description: "Drag the edge, or focus it and use the arrow keys.",
    group: "Behaviour",
    type: "boolean",
    default: true,
  },
  { key: "maxHeight", label: "Height before scrolling (px)", description: "0 means no limit.", group: "Style", type: "number", default: 320, min: 0, max: 800 },
  {
    key: "theme",
    label: "Theme",
    description: "Light, dark, or whatever the visitor's device is set to.",
    group: "Style",
    type: "select",
    default: "light",
    options: ["light", "dark", "system"],
  },
  { key: "accentColor", label: "Accent colour", description: "Focus rings.", group: "Style", type: "color", default: "#1d4ed8" },
  {
    key: "sortedText",
    label: "Sorted",
    description: "Said after sorting. {column} and {direction} are filled in.",
    group: "Words",
    type: "text",
    default: "Sorted by {column}, {direction}",
    maxLength: 80,
  },
  {
    key: "ascendingText",
    label: "Ascending",
    description: "The direction, A to Z.",
    group: "Words",
    type: "text",
    default: "ascending",
    maxLength: 30,
  },
  {
    key: "descendingText",
    label: "Descending",
    description: "The direction, Z to A.",
    group: "Words",
    type: "text",
    default: "descending",
    maxLength: 30,
  },
  {
    key: "notSortedText",
    label: "Not sorted",
    description: "Said before any sorting.",
    group: "Words",
    type: "text",
    default: "Not sorted",
    maxLength: 40,
  },
  {
    key: "widthLabel",
    label: "Width handle",
    description: "Read out for a column's resize handle. {column} is the column.",
    group: "Words",
    type: "text",
    default: "{column} column width",
    maxLength: 60,
  },
  {
    key: "pixelsText",
    label: "Width",
    description: "Read out as it resizes. {width} is the number.",
    group: "Words",
    type: "text",
    default: "{width} pixels",
    maxLength: 30,
  },
  {
    key: "nameHeader",
    label: "Name column",
    description: "Heads the first column.",
    group: "Words",
    type: "text",
    default: "Name",
    maxLength: 30,
  },
  {
    key: "ownerHeader",
    label: "Owner column",
    description: "Heads the second column.",
    group: "Words",
    type: "text",
    default: "Owner",
    maxLength: 30,
  },
  {
    key: "statusHeader",
    label: "Status column",
    description: "Heads the third column.",
    group: "Words",
    type: "text",
    default: "Status",
    maxLength: 30,
  },
  {
    key: "updatedHeader",
    label: "Updated column",
    description: "Heads the last column.",
    group: "Words",
    type: "text",
    default: "Updated",
    maxLength: 30,
  },
] as const satisfies Schema;

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

// Compile error if the schema and the component's config type drift apart.
export const schemaMatchesComponent: Same<ConfigOf<typeof dataGridSchema>, DataGridConfig> = true;
